; editor-syntax injections query for cpp. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-cpp@0.23.4 queries/injections.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["cpp/injections"].

(raw_string_literal
  delimiter: (raw_string_delimiter) @injection.language
  (raw_string_content) @injection.content)
