; editor-syntax highlights query for vue. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/vue/highlights.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["vue/highlights"].

(tag_name) @tag

(end_tag) @tag

(directive_name) @keyword

(directive_argument) @constant

(attribute
  (attribute_name) @attribute
  [(attribute_value) (quoted_attribute_value)]? @string)

(directive_attribute
  (directive_name) @attribute
  (directive_argument)? @attribute
  (directive_modifiers)? @attribute
  [(attribute_value) (quoted_attribute_value)]? @string)

(comment) @comment

[
  "<"
  ">"
  "</"
  "{{"
  "}}"
  "/>" 
] @punctuation.bracket

"=" @punctuation.delimiter
