#!/usr/bin/env python3
"""Generate src/commonTest/.../CodecGolden.kt from the golden codec fixtures.

The fixtures (fixtures/codec/*.bin) are written by the native bridge test
(`ST_WRITE_GOLDEN=1 ST_FIXTURES_DIR=... terminal_bridge_test`) and compared
byte-for-byte by every later native run. This script embeds the same bytes in
Kotlin so ViewportCodecTest decodes exactly what the C encoder produced.

usage: gen_codec_golden.py [--check] <fixtures/codec> <CodecGolden.kt>
  --check  exit 1 if the Kotlin file differs from what would be generated
"""
import os
import sys


def render(fixtures):
    names = sorted(f for f in os.listdir(fixtures) if f.endswith(".bin"))
    out = [
        "// GENERATED by native/scripts/gen_codec_golden.py from fixtures/codec/*.bin - do not edit.",
        "// The native bridge test asserts it still produces these exact bytes.",
        "package dev.supermux.terminal",
        "",
        "internal object CodecGolden {",
    ]
    for name in names:
        data = open(os.path.join(fixtures, name), "rb").read()
        ident = name[:-4].upper()
        h = data.hex()
        chunks = [h[i:i + 96] for i in range(0, len(h), 96)] or [""]
        out.append(f"    /** fixtures/codec/{name} ({len(data)} bytes) */")
        out.append(f"    val {ident}: ByteArray get() = hex(")
        for i, c in enumerate(chunks):
            sep = " +" if i < len(chunks) - 1 else ","
            out.append(f'        "{c}"{sep}')
        out.append("    )")
        out.append("")
    out.append("    private fun hex(s: String): ByteArray =")
    out.append("        ByteArray(s.length / 2) { ((s[2 * it].digitToInt(16) shl 4) or s[2 * it + 1].digitToInt(16)).toByte() }")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    args = sys.argv[1:]
    check = False
    if args and args[0] == "--check":
        check = True
        args = args[1:]
    fixtures, target = args
    text = render(fixtures)
    if check:
        current = open(target).read() if os.path.exists(target) else ""
        if current != text:
            print(f"{target} is out of date with {fixtures}", file=sys.stderr)
            sys.exit(1)
        return
    with open(target, "w") as f:
        f.write(text)
    print(f"wrote {target}", file=sys.stderr)


if __name__ == "__main__":
    main()
