; editor-syntax folds query for javascript. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/javascript/folds.scm (Apache-2.0)
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/ecma/folds.scm (Apache-2.0)
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/jsx/folds.scm (Apache-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["javascript/folds"].

[
  (arguments)
  (for_in_statement)
  (for_statement)
  (while_statement)
  (arrow_function)
  (function_expression)
  (function_declaration)
  (class_declaration)
  (method_definition)
  (do_statement)
  (with_statement)
  (switch_statement)
  (switch_case)
  (switch_default)
  (import_statement)+
  (if_statement)
  (try_statement)
  (catch_clause)
  (array)
  (object)
  (generator_function)
  (generator_function_declaration)
] @fold

(jsx_element) @fold
