; editor-syntax folds query for ruby. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/ruby/folds.scm (Apache-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["ruby/folds"].

[
  (method)
  (singleton_method)
  (class)
  (module)
  (if)
  (else)
  (case)
  (do_block)
  (singleton_class)
  (lambda)
] @fold
