; editor-syntax highlights query for ruby. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-ruby@0.23.1 queries/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["ruby/highlights"].

(identifier) @variable

[
  "alias"
  "and"
  "begin"
  "break"
  "case"
  "class"
  "def"
  "do"
  "else"
  "elsif"
  "end"
  "ensure"
  "for"
  "if"
  "in"
  "module"
  "next"
  "or"
  "rescue"
  "retry"
  "return"
  "then"
  "unless"
  "until"
  "when"
  "while"
  "yield"
] @keyword

(constant) @constructor

"defined?" @function.method.builtin

[
  (class_variable)
  (instance_variable)
] @property

(file) @constant.builtin

(line) @constant.builtin

(encoding) @constant.builtin

[
  (self)
  (super)
] @variable.builtin

[
  (string)
  (bare_string)
  (subshell)
  (heredoc_body)
  (heredoc_beginning)
] @string

[
  (simple_symbol)
  (delimited_symbol)
  (hash_key_symbol)
  (bare_symbol)
] @string.special.symbol

(regex) @string.special.regex

(escape_sequence) @escape

[
  (integer)
  (float)
] @number

[
  (nil)
  (true)
  (false)
] @constant.builtin

(comment) @comment

[
"="
"=>"
"->"
] @operator

[
  ","
  ";"
  "."
] @punctuation.delimiter

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
  "%w("
  "%i("
] @punctuation.bracket

((identifier) @function.method
 )

((identifier) @keyword
 (#match? @keyword "^(private|protected|public)$"))

(call
  method: [(identifier) (constant)] @function.method)

((identifier) @function.method.builtin
 (#eq? @function.method.builtin "require"))

(alias (identifier) @function.method)

(setter (identifier) @function.method)

(method name: [(identifier) (constant)] @function.method)

(singleton_method name: [(identifier) (constant)] @function.method)

((identifier) @constant.builtin
 (#match? @constant.builtin "^__(FILE|LINE|ENCODING)__$"))

(hash_splat_nil
  "**" @operator) @constant.builtin

((constant) @constant
 (#match? @constant "^[A-Z\\p{Nd}_]+$"))

(block_parameter (identifier) @variable.parameter)

(block_parameters (identifier) @variable.parameter)

(destructured_parameter (identifier) @variable.parameter)

(hash_splat_parameter (identifier) @variable.parameter)

(lambda_parameters (identifier) @variable.parameter)

(method_parameters (identifier) @variable.parameter)

(splat_parameter (identifier) @variable.parameter)

(keyword_parameter name: (identifier) @variable.parameter)

(optional_parameter name: (identifier) @variable.parameter)

(interpolation
  "#{" @punctuation.special
  "}" @punctuation.special) @embedded
