; editor-syntax highlights query for toml. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   @tree-sitter-grammars/tree-sitter-toml@0.7.0 queries/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["toml/highlights"].

(bare_key) @type

(quoted_key) @string

(boolean) @boolean

(comment) @comment

(string) @string

[
  (integer)
  (float)
] @number

[
  (offset_date_time)
  (local_date_time)
  (local_date)
  (local_time)
] @string.special

[
  "."
  ","
] @punctuation.delimiter

"=" @operator

[
  "["
  "]"
  "[["
  "]]"
  "{"
  "}"
] @punctuation.bracket

(pair
  (bare_key)) @property

(pair
  (dotted_key
    (bare_key) @property))
