; editor-syntax injections query for ocaml_interface. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/ocaml-interface/injections.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["ocaml_interface/injections"].

((comment) @injection.content
 (#set! injection.language "comment"))
