import { describe, test, expect, beforeEach, afterEach } from "bun:test"
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync, statSync, mkdirSync, symlinkSync, lstatSync } from "fs"
import { join } from "path"
import { tmpdir } from "os"
import { prepareCodexEnvironment } from "../src/environment/index.js"
import type { CodexEnvironmentSpec, McpServerSpec } from "../src/environment/index.js"

function jwt(exp: number): string {
  return ["e30", Buffer.from(JSON.stringify({ exp })).toString("base64url"), "sig"].join(".")
}

function authJson(exp: number): string {
  return JSON.stringify({ tokens: { access_token: jwt(exp) } })
}

const MUX_SHIM: McpServerSpec = {
  name: "mux-shim",
  command: "bun",
  args: ["run", "/path/to/shim/index.ts"],
  env: {
    MUX_SESSION_ID: "zoom",
    MUX_DISPLAY_NAME: "zoom",
    MUX_AGENT_KIND: "codex",
    MUX_SOCKETS_DIR: "/sockets",
  },
}

/** Captured from the broker writeCodexConfig for the same inputs before the move. */
const CODEX_TOML = `# Generated by supermux. Do not edit by hand.

[mcp_servers.mux-shim]
command = "bun"
args = ["run","/path/to/shim/index.ts"]
env.MUX_SESSION_ID = "zoom"
env.MUX_DISPLAY_NAME = "zoom"
env.MUX_AGENT_KIND = "codex"
env.MUX_SOCKETS_DIR = "/sockets"

# Disable codex's native memory feature — ~/.mux is the sole memory.
[features]
memories = false
`

describe("prepareCodexEnvironment", () => {
  let dir: string
  beforeEach(() => { dir = mkdtempSync(join(tmpdir(), "codex-env-")) })
  afterEach(() => { rmSync(dir, { recursive: true, force: true }) })

  function spec(over: Partial<CodexEnvironmentSpec> = {}): CodexEnvironmentSpec {
    return {
      home: join(dir, "session"),
      workdir: join(dir, "wd"),
      mcpServers: [MUX_SHIM],
      skillsPaths: [],
      instructions: null,
      credentials: { apiKey: "sk-test", canonicalHome: join(dir, "canonical") },
      nativeMemory: false,
      ...over,
    }
  }

  test("config.toml matches the former broker writer byte-for-byte", async () => {
    const prepared = await prepareCodexEnvironment(spec())
    const path = join(dir, "session", "config.toml")
    expect(prepared.files).toContain(path)
    expect(readFileSync(path, "utf8")).toBe(CODEX_TOML)
  })

  test("apiKey wins and does not copy auth.json", async () => {
    mkdirSync(join(dir, "canonical"), { recursive: true })
    writeFileSync(join(dir, "canonical", "auth.json"), authJson(2000))
    const prepared = await prepareCodexEnvironment(spec({ credentials: { apiKey: "sk-test", canonicalHome: join(dir, "canonical") } }))
    expect(prepared.credentials).toBe("api_key")
    expect(prepared.env.OPENAI_API_KEY).toBe("sk-test")
    expect(prepared.env.CODEX_HOME).toBe(join(dir, "session"))
    expect(existsSync(join(dir, "session", "auth.json"))).toBe(false)
  })

  test("copies canonical auth.json after promoteIfNewer", async () => {
    const canonicalHome = join(dir, "canonical")
    mkdirSync(canonicalHome, { recursive: true })
    writeFileSync(join(canonicalHome, "auth.json"), authJson(2000))
    const prepared = await prepareCodexEnvironment(spec({
      credentials: { apiKey: null, canonicalHome },
    }))
    expect(prepared.credentials).toBe("copy")
    expect(prepared.env.OPENAI_API_KEY).toBeUndefined()
    expect(readFileSync(join(dir, "session", "auth.json"), "utf8")).toBe(authJson(2000))
    expect(statSync(join(dir, "session", "auth.json")).mode & 0o777).toBe(0o600)
    expect(prepared.files).toContain(join(dir, "session", "auth.json"))
  })

  test("throws when neither apiKey nor canonical auth exists", async () => {
    const canonicalHome = join(dir, "canonical")
    mkdirSync(canonicalHome, { recursive: true })
    await expect(prepareCodexEnvironment(spec({
      credentials: { apiKey: null, canonicalHome },
    }))).rejects.toThrow(/Codex auth not found/)
  })

  test("heals a newer session copy into the canonical file before copying", async () => {
    const canonicalHome = join(dir, "canonical")
    const sessionHome = join(dir, "session")
    mkdirSync(canonicalHome, { recursive: true })
    mkdirSync(sessionHome, { recursive: true })
    writeFileSync(join(canonicalHome, "auth.json"), authJson(1000))
    writeFileSync(join(sessionHome, "auth.json"), authJson(3000))
    await prepareCodexEnvironment(spec({
      home: sessionHome,
      credentials: { apiKey: null, canonicalHome },
    }))
    expect(readFileSync(join(canonicalHome, "auth.json"), "utf8")).toBe(authJson(3000))
    expect(readFileSync(join(sessionHome, "auth.json"), "utf8")).toBe(authJson(3000))
  })

  test("instructions write AGENTS.md at 0600 in CODEX_HOME", async () => {
    const prepared = await prepareCodexEnvironment(spec({ instructions: "hello-codex" }))
    const dest = join(dir, "session", "AGENTS.md")
    expect(prepared.files).toContain(dest)
    expect(readFileSync(dest, "utf8")).toBe("hello-codex")
    expect(statSync(dest).mode & 0o777).toBe(0o600)
  })

  test("refuses to write AGENTS.md through a symlink; target is untouched", async () => {
    const victim = join(dir, "victim")
    writeFileSync(victim, "keep-me")
    mkdirSync(join(dir, "session"), { recursive: true })
    symlinkSync(victim, join(dir, "session", "AGENTS.md"))
    await expect(prepareCodexEnvironment(spec({ instructions: "pwned" }))).rejects.toThrow(/refusing to write through symlink/)
    expect(readFileSync(victim, "utf8")).toBe("keep-me")
  })

  test("dest symlink to canonical auth is unlinked; canonical unchanged; session copy is a regular file", async () => {
    const canonicalHome = join(dir, "canonical")
    mkdirSync(canonicalHome, { recursive: true })
    mkdirSync(join(dir, "session"), { recursive: true })
    const canonical = join(canonicalHome, "auth.json")
    writeFileSync(canonical, authJson(2000))
    symlinkSync(canonical, join(dir, "session", "auth.json"))
    await prepareCodexEnvironment(spec({ credentials: { apiKey: null, canonicalHome } }))
    expect(readFileSync(canonical, "utf8")).toBe(authJson(2000))
    expect(lstatSync(join(dir, "session", "auth.json")).isSymbolicLink()).toBe(false)
    expect(statSync(join(dir, "session", "auth.json")).isFile()).toBe(true)
  })

  test("injected MCP name throws TypeError and writes nothing", async () => {
    await expect(prepareCodexEnvironment(spec({
      mcpServers: [{ name: 'x]\\ncommand = "pwned"', command: "true", args: [], env: {} }],
    }))).rejects.toThrow(/mcpServers\[0\]\.name/)
    expect(existsSync(join(dir, "session", "config.toml"))).toBe(false)
  })

  test("requireSpec TypeError names each missing field", async () => {
    const full: any = spec()
    for (const field of ["home", "workdir", "mcpServers", "skillsPaths", "instructions", "nativeMemory", "credentials"]) {
      const s = { ...full }; delete s[field]
      await expect(prepareCodexEnvironment(s)).rejects.toThrow(new RegExp(`${field} is required`))
    }
    await expect(prepareCodexEnvironment({ ...full, credentials: { canonicalHome: join(dir, "c") } } as any)).rejects.toThrow(/credentials.apiKey is required/)
  })

  test("files lists exactly what was written for apiKey + instructions", async () => {
    const prepared = await prepareCodexEnvironment(spec({ instructions: "body" }))
    expect(prepared.files.sort()).toEqual([
      join(dir, "session", "AGENTS.md"),
      join(dir, "session", "config.toml"),
    ].sort())
  })
})
