import { test, expect } from "bun:test"
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from "fs"
import { join } from "path"
import { tmpdir } from "os"
import { prepareGrokEnvironment } from "../src/environment/index.js"
import type { GrokEnvironmentSpec, McpServerSpec } from "../src/environment/index.js"

function home(): string { return mkdtempSync(join(tmpdir(), "mux-grok-home-")) }

function auth(expiresAt: string, token: string): string {
  return JSON.stringify({
    "https://auth.x.ai::account": {
      expires_at: expiresAt,
      key: token,
      refresh_token: `refresh-${token}`,
    },
  })
}

const MUX_SHIM: McpServerSpec = {
  name: "mux-shim",
  command: "bun",
  args: ["run", "/opt/mux/shim.ts"],
  env: {
    MUX_SESSION_ID: "sess-1",
    MUX_DISPLAY_NAME: "cool-session",
    MUX_AGENT_KIND: "grok",
    MUX_SOCKETS_DIR: "/run/mux/sockets",
  },
}

/** Captured from the broker writeGrokConfig for the same inputs before the move. */
const GROK_TOML_NO_SKILLS = `# Generated by supermux — session-private grok config. Do not edit.
[cli]
# grok defaults to checking for updates on every launch, and the broker launches a
# child per session — so the binary could change mid-conversation, versions could
# drift between concurrent sessions, and every spawn would pay a network round-trip.
# Pinned off for broker-driven sessions only; the user's own ~/.grok/config.toml is
# untouched, so interactive \`grok\` still auto-updates as they configured it.
auto_update = false

[claude_compat]
imported = true
[mcp_servers.mux-shim]
command = "bun"
args = ["run", "/opt/mux/shim.ts"]
enabled = true

[mcp_servers.mux-shim.env]
MUX_SESSION_ID = "sess-1"
MUX_DISPLAY_NAME = "cool-session"
MUX_AGENT_KIND = "grok"
MUX_SOCKETS_DIR = "/run/mux/sockets"
`

function grokSpec(over: Partial<GrokEnvironmentSpec> & Pick<GrokEnvironmentSpec, "home" | "workdir" | "credentials">): GrokEnvironmentSpec {
  return {
    sessionId: "sess-1",
    sessionName: "cool-session",
    mcpServers: [MUX_SHIM],
    skillsPaths: [],
    instructions: null,
    autoUpdate: false,
    importClaudeConfig: false,
    platform: "linux",
    ...over,
  }
}

test("prepareGrokEnvironment config.toml matches the former broker writer byte-for-byte", async () => {
  const sessionHome = home()
  const prepared = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: join(sessionHome, "missing-auth.json") },
  }))
  const path = join(sessionHome, ".grok", "config.toml")
  expect(prepared.files).toEqual([path])
  expect(readFileSync(path, "utf8")).toBe(GROK_TOML_NO_SKILLS)
})

test("prepareGrokEnvironment escapes paths that would break the TOML", async () => {
  const sessionHome = home()
  await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: join(sessionHome, "missing.json") },
    mcpServers: [{
      name: "mux-shim",
      command: "bun",
      args: ["run", '/weird/pa"th\\x.ts'],
      env: {
        MUX_SESSION_ID: "s",
        MUX_DISPLAY_NAME: 'quote"name',
        MUX_AGENT_KIND: "grok",
        MUX_SOCKETS_DIR: "/s",
      },
    }],
  }))
  const toml = readFileSync(join(sessionHome, ".grok", "config.toml"), "utf8")
  expect(toml).toContain('"/weird/pa\\"th\\\\x.ts"')
  expect(toml).toContain('MUX_DISPLAY_NAME = "quote\\"name"')
})

test("prepareGrokEnvironment declares [skills] paths", async () => {
  const sessionHome = home()
  await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: join(sessionHome, "missing.json") },
    skillsPaths: ["/plugins/mux-core/skills", '/plugins/we"ird/skills'],
    mcpServers: [{
      name: "mux-shim",
      command: "bun",
      args: ["run", "/s.ts"],
      env: { MUX_SESSION_ID: "i", MUX_DISPLAY_NAME: "n", MUX_AGENT_KIND: "grok", MUX_SOCKETS_DIR: "/d" },
    }],
  }))
  const toml = readFileSync(join(sessionHome, ".grok", "config.toml"), "utf8")
  expect(toml).toContain('[skills]\npaths = ["/plugins/mux-core/skills", "/plugins/we\\"ird/skills"]')
})

test("prepareGrokEnvironment omits [skills] when paths are empty", async () => {
  const sessionHome = home()
  await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: join(sessionHome, "missing.json") },
    skillsPaths: [],
  }))
  expect(readFileSync(join(sessionHome, ".grok", "config.toml"), "utf8")).not.toContain("[skills]")
})

test("instructions go to AGENTS.md, or AGENTS.override.md when AGENTS.md exists, and git-exclude", async () => {
  const sessionHome = home()
  const workdir = home()
  mkdirSync(join(workdir, ".git", "info"), { recursive: true })
  const a = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir,
    credentials: { canonicalAuthPath: join(sessionHome, "missing.json") },
    instructions: "first",
  }))
  expect(a.files).toContain(join(workdir, "AGENTS.md"))
  expect(readFileSync(join(workdir, "AGENTS.md"), "utf8")).toBe("first")
  expect(readFileSync(join(workdir, ".git", "info", "exclude"), "utf8")).toContain("AGENTS.md")

  const b = await prepareGrokEnvironment(grokSpec({
    home: home(),
    workdir,
    credentials: { canonicalAuthPath: join(sessionHome, "missing.json") },
    instructions: "override-body",
  }))
  expect(b.files).toContain(join(workdir, "AGENTS.override.md"))
  expect(readFileSync(join(workdir, "AGENTS.override.md"), "utf8")).toBe("override-body")
  expect(readFileSync(join(workdir, ".git", "info", "exclude"), "utf8")).toContain("AGENTS.override.md")
})

test("canonical auth exists → credentials canonical and GROK_AUTH_PATH points at it", async () => {
  const userGrokDir = home()
  const sessionHome = home()
  const canonical = join(userGrokDir, "auth.json")
  writeFileSync(canonical, '{"token":"abc"}')
  const res = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: canonical },
  }))
  expect(res.credentials).toBe("canonical")
  expect(res.env.HOME).toBe(sessionHome)
  expect(res.env.GROK_AUTH_PATH).toBe(canonical)
  expect(existsSync(join(sessionHome, ".grok", "auth.json"))).toBe(false)
})

test("missing canonical auth fails open with credentials none", async () => {
  const sessionHome = home()
  const canonical = join(tmpdir(), "definitely-missing-grok-dir", "auth.json")
  const res = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: canonical },
  }))
  expect(res.credentials).toBe("none")
  expect(res.env.GROK_AUTH_PATH).toBe(canonical)
  expect(existsSync(join(sessionHome, ".grok"))).toBe(true)
})

test("legacy private newer than canonical is promoted", async () => {
  const userGrokDir = home()
  const sessionHome = home()
  const sessionGrokDir = join(sessionHome, ".grok")
  mkdirSync(sessionGrokDir)
  const canonical = join(userGrokDir, "auth.json")
  writeFileSync(canonical, auth("2026-07-26T15:41:47Z", "stale"))
  writeFileSync(join(sessionGrokDir, "auth.json"), auth("2026-07-26T18:33:13Z", "refreshed"))
  const res = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: canonical },
  }))
  expect(res.credentials).toBe("canonical")
  expect(readFileSync(canonical, "utf8")).toBe(auth("2026-07-26T18:33:13Z", "refreshed"))
  expect(res.env.GROK_AUTH_PATH).toBe(canonical)
})

test("stale private copy does not overwrite newer canonical auth", async () => {
  const userGrokDir = home()
  const sessionHome = home()
  mkdirSync(join(sessionHome, ".grok"))
  const canonical = join(userGrokDir, "auth.json")
  writeFileSync(canonical, auth("2026-07-26T18:33:13Z", "canonical"))
  writeFileSync(join(sessionHome, ".grok", "auth.json"), auth("2026-07-26T15:41:47Z", "stale"))
  await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: canonical },
  }))
  expect(readFileSync(canonical, "utf8")).toBe(auth("2026-07-26T18:33:13Z", "canonical"))
})

test("private credential is recovered when the canonical file is missing", async () => {
  const userGrokDir = home()
  const sessionHome = home()
  mkdirSync(join(sessionHome, ".grok"))
  const canonical = join(userGrokDir, "auth.json")
  const credential = auth("2026-07-26T18:33:13Z", "only-copy")
  writeFileSync(join(sessionHome, ".grok", "auth.json"), credential)
  const res = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: canonical },
  }))
  expect(res.credentials).toBe("canonical")
  expect(readFileSync(canonical, "utf8")).toBe(credential)
  expect(res.env.GROK_AUTH_PATH).toBe(canonical)
})

test("an atomic Grok refresh stays visible to sibling sessions", async () => {
  const userGrokDir = home()
  const firstHome = home()
  const secondHome = home()
  const canonical = join(userGrokDir, "auth.json")
  writeFileSync(canonical, '{"token":"initial"}')
  const first = await prepareGrokEnvironment(grokSpec({ home: firstHome, workdir: firstHome, credentials: { canonicalAuthPath: canonical } }))
  const second = await prepareGrokEnvironment(grokSpec({ home: secondHome, workdir: secondHome, credentials: { canonicalAuthPath: canonical } }))
  const replacement = join(userGrokDir, "auth.next")
  writeFileSync(replacement, '{"token":"rotated"}')
  renameSync(replacement, first.env.GROK_AUTH_PATH!)
  expect(second.env.GROK_AUTH_PATH).toBe(first.env.GROK_AUTH_PATH)
  expect(readFileSync(second.env.GROK_AUTH_PATH!, "utf8")).toBe('{"token":"rotated"}')
})

test("USERPROFILE is set on win32", async () => {
  const sessionHome = home()
  const res = await prepareGrokEnvironment(grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: join(tmpdir(), "missing-grok", "auth.json") },
    platform: "win32",
  }))
  expect(res.env.USERPROFILE).toBe(sessionHome)
})

test("config rewrite is idempotent", async () => {
  const sessionHome = home()
  const spec = grokSpec({
    home: sessionHome,
    workdir: sessionHome,
    credentials: { canonicalAuthPath: join(sessionHome, "missing.json") },
  })
  await prepareGrokEnvironment(spec)
  const a = readFileSync(join(sessionHome, ".grok", "config.toml"), "utf8")
  await prepareGrokEnvironment(spec)
  expect(readFileSync(join(sessionHome, ".grok", "config.toml"), "utf8")).toBe(a)
  expect(statSync(join(sessionHome, ".grok", "config.toml")).mode & 0o777).toBe(0o600)
})
