; editor-syntax highlights query for json. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-json@0.24.8 queries/highlights.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["json/highlights"].

(pair
  key: (_) @string.special.key)

(string) @string

(number) @number

[
  (null)
  (true)
  (false)
] @constant.builtin

(escape_sequence) @escape

(comment) @comment
