; editor-syntax folds query for dart. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-dart@1.0.0 queries/folds.scm (ISC)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["dart/folds"].

[
  (class_definition)
	(enum_declaration)

  (function_body)

	(block)
] @fold
