; editor-syntax highlights query for dart. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-dart@1.0.0 queries/highlights.scm (ISC)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["dart/highlights"].

(dotted_identifier_list) @string

(super) @function

(annotation
  name: (identifier) @attribute)

(marker_annotation
  name: (identifier) @attribute)

(template_substitution
  "$" @punctuation.special
  "{" @punctuation.special
  "}" @punctuation.special
) @none

(template_substitution
  "$" @punctuation.special
  (identifier_dollar_escaped) @variable
) @none

(escape_sequence) @string.escape

[
 "@"
 "=>"
 ".."
 "??"
 "=="
 "?"
 ":"
 "&&"
 "%"
 "<"
 ">"
 "="
 ">="
 "<="
 "||"
 (increment_operator)
 (is_operator)
 (prefix_operator)
 (equality_operator)
 (additive_operator)
] @operator

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
]  @punctuation.bracket

[
  ";"
  "."
  ","
] @punctuation.delimiter

(class_definition
  name: (identifier) @type)

(constructor_signature
  name: (identifier) @type)

(scoped_identifier
  scope: (identifier) @type)

(function_signature
  name: (identifier) @method)

(getter_signature
  (identifier) @method)

(setter_signature
  name: (identifier) @method)

(enum_declaration
  name: (identifier) @type)

(enum_constant
  name: (identifier) @type)

(type_identifier) @type

(void_type) @type

((scoped_identifier
  scope: (identifier) @type
  name: (identifier) @type)
 (#match? @type "^[a-zA-Z]"))

(type_identifier) @type

(inferred_type) @keyword

(const_builtin) @constant.builtin

(final_builtin) @constant.builtin

((identifier) @type
 (#match? @type "^_?[A-Z]"))

("Function" @type)

(unconditional_assignable_selector
  (identifier) @property)

(assignment_expression
  left: (assignable_expression) @variable)

(this) @variable.builtin

(formal_parameter
    name: (identifier) @parameter)

(named_argument
  (label (identifier) @parameter))

[
    (hex_integer_literal)
    (decimal_integer_literal)
    (decimal_floating_point_literal)
    ; TODO: inaccessbile nodes
    ; (octal_integer_literal)
    ; (hex_floating_point_literal)
] @number

(symbol_literal) @symbol

(string_literal) @string

(true) @boolean

(false) @boolean

(null_literal) @constant.builtin

(documentation_comment) @comment

(comment) @comment

["import" "library" "export"] @include

[
    ; "assert"
    (case_builtin)
    "extension"
    "on"
    "class"
    "enum"
    "extends"
    "in"
    "is"
    "new"
    "return"
    "super"
    "with"
] @keyword

[
    "abstract"
    "as"
    "async"
    "async*"
    "yield"
    "sync*"
    "await"
    "covariant"
    "deferred"
    "dynamic"
    "external"
    "factory"
    "get"
    "implements"
    "interface"
    "library"
    "operator"
    "mixin"
    "part"
    "set"
    "show"
    "static"
    "typedef"
] @keyword

["if" "else" "switch" "default"] @conditional

[
  "try"
  "throw"
  "catch"
  "finally"
  (break_statement)
] @exception

["do" "while" "continue" "for"] @repeat

(ERROR) @error
