; editor-syntax folds query for elm. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/elm/folds.scm (Apache-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["elm/folds"].

[
  (case_of_branch)
  (case_of_expr)
  (value_declaration)
  (type_declaration)
  (type_alias_declaration)
  (list_expr)
  (record_expr)
  (parenthesized_expr)
  (import_clause)+
] @fold
