; editor-syntax highlights query for elm. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   @elm-tooling/tree-sitter-elm@5.9.4 queries/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["elm/highlights"].

[
    "if"
    "then"
    "else"
    "let"
    "in"
 ] @keyword.control.elm

(case) @keyword.control.elm

(of) @keyword.control.elm

(colon) @keyword.other.elm

(backslash) @keyword.other.elm

(as) @keyword.other.elm

(port) @keyword.other.elm

(exposing) @keyword.other.elm

(alias) @keyword.other.elm

(infix) @keyword.other.elm

(arrow) @keyword.operator.arrow.elm

(port) @keyword.other.port.elm

(lower_pattern) @local.function.elm

(record_base_identifier) @local.function.elm

(operator_identifier) @keyword.operator.elm

(eq) @keyword.operator.assignment.elm

"(" @punctuation.section.braces

")" @punctuation.section.braces

"|" @keyword.other.elm

"," @punctuation.separator.comma.elm

(import) @meta.import.elm

(module) @keyword.other.elm

(number_constant_expr) @constant.numeric.elm

(type) @keyword.type.elm

(type_ref) @storage.type.elm

(union_pattern) @union.elm

(line_comment) @comment.elm

(block_comment) @comment.elm

(string_escape) @character.escape.elm

(open_quote) @string.elm

(close_quote) @string.elm

(regular_string_part) @string.elm

(open_char) @char.elm

(close_char) @char.elm

(glsl_content) @source.glsl

(type_annotation(lower_case_identifier) @function.elm)

(port_annotation(lower_case_identifier) @function.elm)

(function_declaration_left(lower_case_identifier) @function.elm)

(function_call_expr target: (value_expr) @function.elm)

(field_access_expr(value_expr(value_qid)) @local.function.elm)

(type_declaration(upper_case_identifier) @storage.type.elm)

(type_alias_declaration name: (upper_case_identifier) @storage.type.elm)

(union_variant(upper_case_identifier) @union.elm)

(value_expr(upper_case_qid(upper_case_identifier)) @union.elm)
