; editor-syntax injections query for elm. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   @elm-tooling/tree-sitter-elm@5.9.4 queries/injections.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["elm/injections"].

((glsl_content) @injection.content
 (#set! injection.language "glsl"))
