import { mkdirSync, writeFileSync } from "fs"
import { join } from "path"

/** TOML basic string. JSON string escaping is a valid subset for the characters
 * that appear in paths/ids (quotes, backslashes, control chars). */
function tomlStr(v: string): string {
  return JSON.stringify(v)
}

/** Write the session-private ~/.grok/config.toml (HOME is redirected to sessionHome).
 *
 * Registers mux-shim as an MCP server here rather than over ACP: grok IGNORES the
 * `mcpServers` param on `session/new` (verified live against 0.2.101 — a server passed
 * that way never registers), so config.toml is the mechanism that actually works.
 *
 * `[claude_compat] imported = true` is grok's marker for "Claude config already
 * imported, don't auto-import again". A private HOME already hides ~/.claude.json, so
 * this is belt-and-braces against grok resolving the user's Claude config another way
 * and re-introducing the global mux-shim/mux-channel. */
export function writeGrokConfig(opts: {
  sessionHome: string
  shimCommand: string
  shimArgs: string[]
  sessionName: string
  sessionId: string
  socketsDir: string
}): string {
  const grokDir = join(opts.sessionHome, ".grok")
  mkdirSync(grokDir, { recursive: true, mode: 0o700 })

  const args = opts.shimArgs.map(tomlStr).join(", ")
  const toml = `# Generated by supermux — session-private grok config. Do not edit.
[claude_compat]
imported = true

[mcp_servers.mux-shim]
command = ${tomlStr(opts.shimCommand)}
args = [${args}]
enabled = true

[mcp_servers.mux-shim.env]
MUX_SESSION_ID = ${tomlStr(opts.sessionId)}
MUX_DISPLAY_NAME = ${tomlStr(opts.sessionName)}
MUX_AGENT_KIND = "grok"
MUX_SOCKETS_DIR = ${tomlStr(opts.socketsDir)}
`
  const path = join(grokDir, "config.toml")
  writeFileSync(path, toml, { encoding: "utf8", mode: 0o600 })
  return path
}
