; editor-syntax folds query for kotlin. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/kotlin/folds.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["kotlin/folds"].

[
	(import_list)

	(when_expression)
	(control_structure_body)

	(lambda_literal)
	(function_body)
	(primary_constructor)
	(secondary_constructor)
	(anonymous_initializer)

	(class_body)
	(enum_class_body)

	(interpolated_expression)
] @fold
