; editor-syntax highlights query for kotlin. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/kotlin/highlights.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["kotlin/highlights"].

(simple_identifier) @variable

((simple_identifier) @variable.builtin
(#eq? @variable.builtin "field"))

((simple_identifier) @variable.builtin
(#eq? @variable.builtin "it"))

[
	"."
	","
	";"
	":"
	"::"
] @punctuation.delimiter

[
	"(" ")"
	"[" "]"
	"{" "}"
] @punctuation.bracket

[
	"!"
	"!="
	"!=="
	"="
	"=="
	"==="
	">"
	">="
	"<"
	"<="
	"||"
	"&&"
	"+"
	"++"
	"+="
	"-"
	"--"
	"-="
	"*"
	"*="
	"/"
	"/="
	"%"
	"%="
	"?."
	"?:"
	"!!"
	"is"
	"in"
	"as"
	"as?"
	".."
	"->"
] @operator

((interpolated_identifier) @variable.builtin
(#eq? @variable.builtin "it"))

((interpolated_identifier) @variable.builtin
(#eq? @variable.builtin "this"))

(type_alias "typealias" @keyword)

[
	(class_modifier)
	(member_modifier)
	(function_modifier)
	(property_modifier)
	(platform_modifier)
	(variance_modifier)
	(parameter_modifier)
	(visibility_modifier)
	(reification_modifier)
	(inheritance_modifier)
]@keyword

[
	"val"
	"var"
	"enum"
	"class"
	"object"
	"interface"
	"companion"
;	"typeof" ; NOTE: It is reserved for future use
] @keyword

("fun") @keyword.function

(jump_expression) @keyword.control.return

[
	"if"
	"else"
	"when"
] @keyword.control.conditional

[
	"for"
	"do"
	"while"
] @keyword.control.repeat

[
	"try"
	"catch"
	"throw"
	"finally"
] @keyword.control.exception

(annotation
	"@" @attribute (use_site_target)? @attribute)

(annotation
	(user_type
		(type_identifier) @attribute))

(annotation
	(constructor_invocation
		(user_type
			(type_identifier) @attribute)))

(file_annotation
	"@" @attribute "file" @attribute ":" @attribute)

(file_annotation
	(user_type
		(type_identifier) @attribute))

(file_annotation
	(constructor_invocation
		(user_type
			(type_identifier) @attribute)))

(character_literal (character_escape_seq) @constant.character.escape)

(string_literal) @string

(character_literal) @constant.character

(boolean_literal) @constant.builtin.boolean

(real_literal) @constant.numeric.float

[
	(integer_literal)
	(long_literal)
	(hex_literal)
	(bin_literal)
	(unsigned_literal)
] @constant.numeric.integer

[
	(line_comment)
	(multiline_comment)
	(shebang_line)
] @comment

(enum_entry
	(simple_identifier) @constant)

((simple_identifier) @constant
(#match? @constant "^[A-Z][A-Z0-9_]*$"))

(_
	(navigation_suffix
		(simple_identifier) @variable.other.member))

(call_expression
	. (simple_identifier) @function)

(call_expression
	(navigation_expression
		(navigation_suffix
			(simple_identifier) @function) . ))

(infix_expression
  . (_) .
	(simple_identifier) @function)

(call_expression
	. (simple_identifier) @function.builtin
    (#match? @function.builtin "^(arrayOf|arrayOfNulls|byteArrayOf|shortArrayOf|intArrayOf|longArrayOf|ubyteArrayOf|ushortArrayOf|uintArrayOf|ulongArrayOf|floatArrayOf|doubleArrayOf|booleanArrayOf|charArrayOf|emptyArray|mapOf|setOf|listOf|emptyMap|emptySet|emptyList|mutableMapOf|mutableSetOf|mutableListOf|print|println|error|TODO|run|runCatching|repeat|lazy|lazyOf|enumValues|enumValueOf|assert|check|checkNotNull|require|requireNotNull|with|suspend|synchronized)$"))

(_
	(navigation_suffix
		(simple_identifier) @constant
		(#match? @constant "^[A-Z][A-Z0-9_]*$")))

((navigation_expression
  . (simple_identifier) @type)
  (#match? @type "^[A-Z]"))

(lambda_literal
	(lambda_parameters
		(variable_declaration
			(simple_identifier) @variable.parameter)))

(parameter_with_optional_type
	(simple_identifier) @variable.parameter)

(parameter
	(simple_identifier) @variable.parameter)

(value_argument
  . (simple_identifier) @variable.parameter)

(anonymous_initializer
	("init") @constructor)

(constructor_invocation
	(user_type
		(type_identifier) @constructor))

(secondary_constructor
	("constructor") @constructor)

(primary_constructor) @constructor

(getter
	("get") @function.builtin)

(setter
	("set") @function.builtin)

(function_declaration
	(modifiers)?
	(type_parameters)?
	(simple_identifier) @function)

(label) @label

(import_header
	(identifier
		(simple_identifier) @function @_import .)
	(import_alias
		(type_identifier) @function)?
		(#match? @_import "^[a-z]"))

(import_header
	(identifier
		(simple_identifier) @type @_import)
	(import_alias
		(type_identifier) @type)?
		(#match? @_import "^[A-Z]"))

(import_header
	"import" @keyword.control.import)

(package_header
	. (identifier)) @namespace

(type_identifier) @type

((type_identifier) @type.builtin
	(#match? @type.builtin "^(Byte|Short|Int|Long|UByte|UShort|UInt|ULong|Float|Double|Boolean|Char|String|Array|ByteArray|ShortArray|IntArray|LongArray|UByteArray|UShortArray|UIntArray|ULongArray|FloatArray|DoubleArray|BooleanArray|CharArray|Map|Set|List|EmptyMap|EmptySet|EmptyList|MutableMap|MutableSet|MutableList)$"))

(type_parameter
  (type_identifier) @type.parameter)

((class_body
	(property_declaration
		(variable_declaration
			(simple_identifier) @variable.other.member)))
  (#not-match? @variable.other.member "^[A-Z][A-Z0-9_]*$"))

(class_parameter
	(simple_identifier) @variable.other.member)

(super_expression) @variable.builtin

(this_expression) @variable.builtin
