; editor-syntax injections query for php. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-php@0.24.2 queries/injections.scm (MIT)
;   tree-sitter-php@0.24.2 queries/injections-text.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["php/injections"].

(heredoc
  (heredoc_body) @injection.content
  (heredoc_end) @injection.language)

(nowdoc
  (nowdoc_body) @injection.content
  (heredoc_end) @injection.language)

((text) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))
