; editor-syntax folds query for fsharp. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-fsharp@0.3.12 queries/folds.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["fsharp/folds"].

[
  (module_defn)
  (function_or_value_defn)
  (member_defn)
  (type_definition)
  (exception_definition)
  (interface_implementation)
  (match_expression)
  (function_expression)
  (rule)
  (if_expression)
  (elif_expression)
  (for_expression)
  (while_expression)
  (try_expression)
  (fun_expression)
  (ce_expression)
  (brace_expression)
  (anon_record_expression)
  (list_expression)
  (array_expression)
  (paren_expression)
  (begin_end_expression)
  (object_expression)
  (literal_expression)
  (block_comment)
  (preproc_if)
] @fold

(line_comment)+ @fold

(xml_doc)+ @fold
