; editor-syntax highlights query for fsharp. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-fsharp@0.3.12 queries/highlights.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["fsharp/highlights"].

[
  (line_comment)
  (xml_doc)
  (block_comment)
] @spell @comment

(xml_doc) @spell @comment.documentation

(const
  [
   (_) @constant
   (unit) @constant.builtin
  ])

(primary_constr_args (_) @variable.parameter)

(class_as_reference
  (_) @variable.parameter.builtin)

((argument_patterns (long_identifier (identifier) @character.special))
 (#match? @character.special "^_"))

(type_name type_name: (_) @type.definition)

(exception_definition exception_name: (_) @type.definition)

[
 (_type)
 (atomic_type)
] @type

(type_argument) @type

(measure_atom (simple_type) @type)

(trait_member_constraint (identifier) @function.member)

(member_signature
  .
  (identifier) @function.member)

(member_signature
  (curried_spec
    (arguments_spec
      "*"* @operator
      (argument_spec
        (argument_name_spec
          "?"? @character.special
          name: (_) @variable.parameter)))))

(union_type_case (identifier) @constructor)

(enum_type_case . (identifier) @constructor)

(union_type_field . (identifier) @variable.member (_))

(rules
  (rule
    pattern: (_) @constant
    block: (_)))

(wildcard_pattern) @character.special

(identifier_pattern
  .
  (_) @constructor
  .
  (_) @variable)

(optional_pattern
  "?" @character.special)

(fsi_directive_decl . (string) @module)

(import_decl . (_) @module)

(named_module
  name: (_) @module)

(namespace
  name: (_) @module)

(module_defn
  (identifier) @module)

(ce_expression
  .
  (_) @constant.macro)

(field_initializer
  field: (_) @property)

(record_fields
  (record_field
    .
    (identifier) @property))

(value_declaration_left . (_) @variable)

(function_declaration_left
  . (_) @function)

(argument_patterns) @variable.parameter

(typed_pattern
  (_pattern) @variable.parameter
  (_type) @type)

(member_defn
  (method_or_prop_defn
    (property_or_ident . (identifier) @function .)
    args: (_)* @variable.parameter))

(member_defn
  (method_or_prop_defn
    (property_or_ident
      instance: (identifier) @variable.parameter.builtin
      method: (identifier) @function.method)
    args: (_)* @variable.parameter))

(member_defn
  (property_or_ident (identifier) @function.member))

(dot_expression
  base: (_) @variable.member
  field: (long_identifier_or_op
    (identifier) @property))

[
  (xint)
  (int)
  (int16)
  (uint16)
  (int32)
  (uint32)
  (int64)
  (uint64)
  (nativeint)
  (unativeint)
] @number

[
  (ieee32)
  (ieee64)
  (float)
  (decimal)
] @number.float

(bool) @boolean

([
  (string)
  (triple_quoted_string)
  (verbatim_string)
  (char)
  (format_string)
  (format_triple_quoted_string)
] @spell @string)

(compiler_directive_decl) @keyword.directive

(preproc_line
  "#line" @keyword.directive)

(attribute
  target: (identifier)? @keyword
  (_type) @attribute)

[
  "("
  ")"
  "{"
  "}"
  "["
  "]"
  "[|"
  "|]"
  "{|"
  "|}"
] @punctuation.bracket

[
  "[<"
  ">]"
] @punctuation.special

(literal_expression
  [
    "<@"
    "@>"
    "<@@"
    "@@>"
  ] @punctuation.special)

(format_string_eval
  [
    "{"
    "}"
  ] @punctuation.special)

[
  ","
  ";"
  ":"
  "."
] @punctuation.delimiter

[
  "|"
  "="
  ">"
  "<"
  "-"
  "~"
  "->"
  "<-"
  "&"
  "&&"
  "|"
  "||"
  ":>"
  ":?>"
  ".."
  (infix_op)
  (prefix_op)
  (op_identifier)
] @operator

(generic_type
  [
   "<"
   ">"
  ] @punctuation.bracket)

(typed_expression
  ">" @punctuation.bracket)

[
  "if"
  "then"
  "else"
  "elif"
  "when"
  "match"
  "match!"
] @keyword.conditional

[
  "and"
  "or"
  "not"
  "upcast"
  "downcast"
] @keyword.operator

[
  "return"
  "return!"
  "yield"
  "yield!"
] @keyword.return

[
  "for"
  "while"
  "downto"
  "to"
] @keyword.repeat

[
  "open"
  "#r"
  "#load"
] @keyword.import

[
  "abstract"
  "delegate"
  "extern"
  "static"
  "inline"
  "mutable"
  "override"
  "rec"
  "global"
  (access_modifier)
] @keyword.modifier

[
  "let"
  "let!"
  "use"
  "use!"
  "and!"
  "member"
] @keyword.function

[
  "enum"
  "type"
  "exception"
  "inherit"
  "interface"
  "and"
  "class"
  "struct"
] @keyword.type

[
  "as"
  "assert"
  "begin"
  "end"
  "done"
  "default"
  "in"
  "do"
  "do!"
  "fun"
  "function"
  "get"
  "set"
  "lazy"
  "new"
  "of"
  "struct"
  "val"
  "module"
  "namespace"
  "with"
] @keyword

[
  "null"
] @constant.builtin

(match_expression "with" @keyword.conditional)

(try_expression
  [
    "try"
    "with"
    "finally"
  ] @keyword.exception)

(preproc_if
  [
    "#if" @keyword.directive
    "#endif" @keyword.directive
  ]
  condition: (_)? @keyword.directive)

(preproc_else
  "#else" @keyword.directive)

(preproc_inactive) @comment

((long_identifier
  (identifier)+ @variable.member
  .
  (identifier)))

(namespace name: (long_identifier (identifier) @module))

(named_module name: (long_identifier (identifier) @module))

(import_decl (long_identifier (identifier) @module))

(module_abbrev (long_identifier (identifier) @module))

(simple_type (long_identifier (identifier) @type))

(attribute (simple_type (long_identifier (identifier) @attribute)))

((simple_type
   (long_identifier
     (identifier) @type.builtin))
 (#any-of? @type.builtin "bool" "byte" "sbyte" "int16" "uint16" "int" "uint" "int64" "uint64" "nativeint" "unativeint" "decimal" "float" "double" "float32" "single" "char" "string" "unit"))

((long_identifier . (identifier) @variable.builtin)
 (#any-of? @variable.builtin "base" "this" "self"))

((long_identifier_or_op (identifier) @variable.builtin)
 (#any-of? @variable.builtin "base" "this" "self"))

((identifier) @module.builtin
 (#any-of? @module.builtin "Array" "Async" "Directory" "File" "List" "Option" "Path" "Map" "Set" "Lazy" "Seq" "Task" "String" "Result" ))

((long_identifier_or_op
   (long_identifier . (identifier) @variable.member (identifier) @property .))
 (#match? @variable.member "^[a-z_]")
 (#not-any-of? @variable.member "this" "base" "self"))

(application_expression
  .
  (long_identifier_or_op
    (identifier) @function.call)
  .
  (_))

(application_expression
  .
  (long_identifier_or_op
    (long_identifier
      (identifier) @function.call .))
  .
  (_))

(application_expression
  .
  (dot_expression
    field: (long_identifier_or_op
      (identifier) @function.call))
  .
  (_))

(application_expression
  .
  (typed_expression
    (long_identifier_or_op
      (identifier) @function.call)
    (_))
  .
  (_))

(application_expression
  .
  (typed_expression
    (long_identifier_or_op
      (long_identifier
        (identifier) @function.call .))
    (_))
  .
  (_))

(application_expression
  .
  (typed_expression
    (dot_expression
      field: (long_identifier_or_op
        (identifier) @function.call))
    (_))
  .
  (_))

((infix_expression
  .
  (_)
  .
  (infix_op) @operator
  .
  [
    (long_identifier_or_op (identifier) @function.call)
    (long_identifier_or_op (long_identifier (identifier) @function.call .))
    (application_expression . (long_identifier_or_op (identifier) @function.call))
    (application_expression . (long_identifier_or_op (long_identifier (identifier) @function.call .)))
    (application_expression . (dot_expression field: (long_identifier_or_op (identifier) @function.call)))
  ])
 (#any-of? @operator "|>" "||>" "|||>"))

((infix_expression
  .
  [
    (long_identifier_or_op (identifier) @function.call)
    (long_identifier_or_op (long_identifier (identifier) @function.call .))
    (application_expression . (long_identifier_or_op (identifier) @function.call))
    (application_expression . (long_identifier_or_op (long_identifier (identifier) @function.call .)))
    (application_expression . (dot_expression field: (long_identifier_or_op (identifier) @function.call)))
  ]
  .
  (infix_op) @operator
  .
  (_))
 (#any-of? @operator "<|" "<||" "<|||"))

((infix_expression
  .
  [
    (long_identifier_or_op (identifier) @function.call)
    (long_identifier_or_op (long_identifier (identifier) @function.call .))
    (application_expression . (long_identifier_or_op (identifier) @function.call))
    (application_expression . (long_identifier_or_op (long_identifier (identifier) @function.call .)))
  ]
  .
  (infix_op) @operator
  .
  [
    (long_identifier_or_op (identifier) @function.call)
    (long_identifier_or_op (long_identifier (identifier) @function.call .))
    (application_expression . (long_identifier_or_op (identifier) @function.call))
    (application_expression . (long_identifier_or_op (long_identifier (identifier) @function.call .)))
  ])
 (#any-of? @operator ">>" "<<"))

((long_identifier_or_op . (identifier) @constructor .)
 (#match? @constructor "^[A-Z]"))

((identifier) @function.builtin
 (#any-of? @function.builtin "typeof" "typedefof" "sizeof" "nameof"))

((identifier) @keyword.exception
 (#any-of? @keyword.exception "failwith" "failwithf" "raise" "reraise"))

((long_identifier_or_op (identifier) @keyword.operator)
 (#eq? @keyword.operator "not"))

((application_expression
   .
   (long_identifier_or_op (identifier) @keyword.operator))
 (#any-of? @keyword.operator
   "leftOuterJoin" "groupJoin" "groupValBy"
   "sortByDescending" "thenBy" "thenByDescending"
   "sortByNullable" "sortByNullableDescending"
   "thenByNullable" "thenByNullableDescending"
   "sumByNullable" "minByNullable" "maxByNullable" "averageByNullable"))

((sequential_expression (long_identifier_or_op (identifier) @keyword.operator))
 (#any-of? @keyword.operator
   "headOrDefault" "lastOrDefault" "exactlyOne" "exactlyOneOrDefault"))

((value_declaration
   (attributes
     (attribute
       (simple_type
         (long_identifier
           (identifier) @attribute))))
   (function_or_value_defn
     (value_declaration_left
       .
       (identifier_pattern (long_identifier_or_op (identifier) @constant)))))
 (#eq? @attribute "Literal"))

((declaration_expression
   (attributes
     (attribute
       (simple_type
         (long_identifier
           (identifier) @attribute))))
   (function_or_value_defn
     (value_declaration_left
       .
       (identifier_pattern (long_identifier_or_op (identifier) @constant)))))
 (#eq? @attribute "Literal"))
