; editor-syntax injections query for fsharp. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-fsharp@0.3.12 queries/injections.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["fsharp/injections"].

((block_comment_content) @injection.content
 (#not-match? @injection.content "^\\*")
 (#set! injection.language "comment"))

((line_comment) @injection.content
 (#set! injection.language "comment"))
