; editor-syntax highlights query for wat. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-wat@0.1.0 queries/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["wat/highlights"].

(block_comment) @comment

(line_comment) @comment

[
  "array"
  "block"
  "catch"
  "catch_ref"
  "catch_all"
  "catch_all_ref"
  "data"
  "declare"
  "elem"
  "else"
  "end"
  "export"
  "field"
  "final"
  "func"
  "global"
  "if"
  "import"
  "item"
  "local"
  "loop"
  "memory"
  "module"
  "mut"
  "null"
  "offset"
  "pagesize"
  "param"
  "rec"
  "ref"
  "result"
  "shared"
  "start"
  "struct"
  "sub"
  "table"
  "tag"
  "then"
  "try_table"
  "type"
  "unshared"
] @keyword

(integer) @number

(float) @number

(instr_name) @operator

[
  "(" ")"
] @punctuation.bracket

(string) @string

(num_type) @type.builtin

(vec_type) @type.builtin

(identifier) @variable

(index) @variable

((block_comment)+ @comment.documentation
  (#match? @comment.documentation "^;;;\\s+.*"))

((ref_type) @type.builtin
 (#match? @type.builtin "^(any|eq|i31|struct|array|null|func|nullfunc|exn|nullexn|extern|nullextern)ref$"))

((heap_type) @type.builtin
 (#match? @type.builtin "^(any|eq|i31|struct|array|null|func|nullfunc|exn|nullexn|extern|nullextern)$"))

(module_field_func
  (identifier) @function)

(extern_type_func
  (identifier) @function)
