#!/usr/bin/env python3
"""gen-registry.py <out.c> <lang>[:bundled] ...  -> the compiled-in grammar list (ses_registry.c).
`lang:bundled` links ses_blob_<lang> (blob_<lang>.c from sestables.py); plain `lang` has code only
and needs ses_language_provide_tables() before first use."""
import sys
out, specs = sys.argv[1], sys.argv[2:]
lines = ['/* generated by tools/gen-registry.py */', '#include "ses_registry.h"', '']
rows = []
for s in specs:
    lang, _, mode = s.partition(':')
    lines.append('ses_grammar *ses_grammar_%s(void);' % lang)
    if mode == 'bundled':
        lines.append('extern const uint8_t ses_blob_%s[];\nextern const uint32_t ses_blob_%s_size;' % (lang, lang))
        rows.append('  {"%s", ses_grammar_%s, ses_blob_%s, &ses_blob_%s_size},' % (lang, lang, lang, lang))
    else:
        rows.append('  {"%s", ses_grammar_%s, 0, 0},' % (lang, lang))
lines += ['', 'const ses_registry_entry ses_registry[] = {'] + rows + ['};',
          'const uint32_t ses_registry_count = %d;' % len(rows)]
open(out, 'w').write('\n'.join(lines) + '\n')
