; editor-syntax folds query for perl. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-perl@2.0.0 queries/folds.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["perl/folds"].

(comment)+ @fold

(pod) @fold

(heredoc_content) @fold

(package_statement (block)) @fold

(class_statement (block)) @fold

[(subroutine_declaration_statement)
 (method_declaration_statement)
 (conditional_statement)
 (loop_statement)
 (for_statement)
 (cstyle_for_statement)
 (block_statement)
 (defer_statement)
 (phaser_statement)] @fold

(try_statement (block) @fold)

(eval_expression (block) @fold)

(anonymous_subroutine_expression) @fold

[(anonymous_array_expression)
 (anonymous_hash_expression)] @fold
