package dev.supermux.desktop.host

import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.FilterQuality
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.painter.BitmapPainter
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.toComposeImageBitmap
import androidx.compose.ui.unit.IntSize
import kotlin.math.roundToInt

/**
 * The tray icon.
 *
 * Compose's `Tray` turns its painter into an AWT `MultiResolutionImage` with one variant at the
 * tray's point size (22×22 on macOS) and one at the screen's scale (44×44 on Retina), drawing the
 * painter at each size. A single 64 px bitmap squeezed into both comes out soft, and a colour icon
 * doesn't match the macOS menu bar. On macOS this draws a black + alpha template (tinted by the OS
 * once `apple.awt.enableTemplateImages` is set) from the bitmap made for that size, 1:1. Windows and
 * Linux keep the colour icon.
 */
object TrayIcons {
    const val COLOUR = "supermux-tray.png"
    /** Template variants (generated by scripts/generate-tray-template.ts), smallest first. */
    val TEMPLATES = listOf("supermux-tray-template-22.png", "supermux-tray-template.png")

    /** JDK 17+ (JDK-8252015): the macOS tray marks its image as a template. Read when AWT's tray loads. */
    const val TEMPLATE_PROPERTY = "apple.awt.enableTemplateImages"

    /** The painter for this OS; falls back to the colour icon when a template can't be loaded. */
    fun painter(mac: Boolean): Painter {
        if (mac) {
            val variants = TEMPLATES.mapNotNull(::load)
            if (variants.size == TEMPLATES.size) return MultiSizeBitmapPainter(variants)
        }
        return BitmapPainter(load(COLOUR) ?: ImageBitmap(1, 1))
    }

    private fun load(name: String): ImageBitmap? = runCatching {
        val bytes = TrayIcons::class.java.classLoader.getResourceAsStream(name)?.use { it.readBytes() } ?: return null
        org.jetbrains.skia.Image.makeFromEncoded(bytes).toComposeImageBitmap()
    }.onFailure { System.err.println("supermux tray: can't load $name: ${it.message}") }.getOrNull()
}

/** Pure: the index of the smallest of [widths] at least [target] px wide, else the widest. */
fun pickVariant(widths: List<Int>, target: Float): Int {
    require(widths.isNotEmpty())
    val fits = widths.indices.filter { widths[it] >= target - 0.5f }
    return fits.minByOrNull { widths[it] } ?: widths.indices.maxBy { widths[it] }
}

/**
 * Draws the variant of [bitmaps] made for the size it is asked to draw at, so each of the tray's
 * resolution variants is a 1:1 copy of a hand-made bitmap rather than a resample of one.
 */
class MultiSizeBitmapPainter(private val bitmaps: List<ImageBitmap>) : Painter() {
    init { require(bitmaps.isNotEmpty()) }

    override val intrinsicSize: Size =
        bitmaps.minBy { it.width }.let { Size(it.width.toFloat(), it.height.toFloat()) }

    override fun DrawScope.onDraw() {
        val bmp = bitmaps[pickVariant(bitmaps.map { it.width }, size.width)]
        val dst = IntSize(size.width.roundToInt(), size.height.roundToInt())
        // 1:1 must copy pixels: High is a Mitchell cubic, which softens even at scale 1.
        val exact = dst.width == bmp.width && dst.height == bmp.height
        drawImage(bmp, dstSize = dst, filterQuality = if (exact) FilterQuality.None else FilterQuality.High)
    }
}
