; editor-syntax folds query for lua. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/lua/folds.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["lua/folds"].

[
 (do_statement)
 (while_statement)
 (repeat_statement)
 (if_statement)
 (for_statement)
 (function_declaration)
 (function_definition)
 (table_constructor)
] @fold
