; editor-syntax injections query for lua. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   @tree-sitter-grammars/tree-sitter-lua@0.4.1 queries/injections.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["lua/injections"].

((function_call
  name: [
    (identifier) @_cdef_identifier
    (_
      _
      (identifier) @_cdef_identifier)
  ]
  arguments: (arguments
    (string
      content: _ @injection.content
      (#set! injection.language "c"))))
  (#eq? @_cdef_identifier "cdef"))
