; editor-syntax folds query for go. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/go/folds.scm (Apache-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["go/folds"].

[
  (const_declaration)
  (expression_switch_statement)
  (expression_case)
  (default_case)
  (type_switch_statement)
  (type_case)
  (for_statement)
  (func_literal)
  (function_declaration)
  (if_statement)
  (import_declaration)
  (method_declaration)
  (type_declaration)
  (var_declaration)
  (composite_literal)
  (literal_element)
  (block)
] @fold
