; editor-syntax highlights query for go. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-go@0.25.0 queries/highlights.scm (MIT)
;   (patterns reversed: written for EARLIER-pattern-wins; this file gives the LATER pattern precedence)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["go/highlights"].

(comment) @comment

[
  (true)
  (false)
  (nil)
  (iota)
] @constant.builtin

[
  (int_literal)
  (float_literal)
  (imaginary_literal)
] @number

(escape_sequence) @escape

[
  (interpreted_string_literal)
  (raw_string_literal)
  (rune_literal)
] @string

[
  "break"
  "case"
  "chan"
  "const"
  "continue"
  "default"
  "defer"
  "else"
  "fallthrough"
  "for"
  "func"
  "go"
  "goto"
  "if"
  "import"
  "interface"
  "map"
  "package"
  "range"
  "return"
  "select"
  "struct"
  "switch"
  "type"
  "var"
] @keyword

[
  "--"
  "-"
  "-="
  ":="
  "!"
  "!="
  "..."
  "*"
  "*"
  "*="
  "/"
  "/="
  "&"
  "&&"
  "&="
  "%"
  "%="
  "^"
  "^="
  "+"
  "++"
  "+="
  "<-"
  "<"
  "<<"
  "<<="
  "<="
  "="
  "=="
  ">"
  ">="
  ">>"
  ">>="
  "|"
  "|="
  "||"
  "~"
] @operator

(identifier) @variable

(field_identifier) @property

(type_identifier) @type

(method_declaration
  name: (field_identifier) @function.method)

(function_declaration
  name: (identifier) @function)

(call_expression
  function: (selector_expression
    field: (field_identifier) @function.method))

(call_expression
  function: (identifier) @function.builtin
  (#match? @function.builtin "^(append|cap|close|complex|copy|delete|imag|len|make|new|panic|print|println|real|recover)$"))

(call_expression
  function: (identifier) @function)
