; editor-syntax injections query for groovy. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/groovy/injections.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["groovy/injections"].

((comment) @injection.content
  (#set! injection.language "comment"))

((groovy_doc) @injection.content
  (#set! injection.language "comment"))
