; editor-syntax highlights query for glsl. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-glsl@0.2.0 queries/highlights.scm (MIT)
;   (patterns reversed: written for EARLIER-pattern-wins; this file gives the LATER pattern precedence)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["glsl/highlights"].

((identifier) @variable.builtin
  (#match? @variable.builtin "^gl_"))

(extension_storage_class) @keyword.storage

"subroutine" @keyword.function

[
  "in"
  "out"
  "inout"
  "uniform"
  "shared"
  "layout"
  "attribute"
  "varying"
  "buffer"
  "coherent"
  "readonly"
  "writeonly"
  "precision"
  "highp"
  "mediump"
  "lowp"
  "centroid"
  "sample"
  "patch"
  "smooth"
  "flat"
  "noperspective"
  "invariant"
  "precise"
] @type.qualifier

(comment) @comment

(identifier) @variable

((identifier) @constant
 (#match? @constant "^[A-Z][A-Z\\d_]*$"))

(sized_type_specifier) @type

(primitive_type) @type

(type_identifier) @type

(statement_identifier) @label

(field_identifier) @property

(preproc_function_def
  name: (identifier) @function.special)

(function_declarator
  declarator: (identifier) @function)

(call_expression
  function: (field_expression
    field: (field_identifier) @function))

(call_expression
  function: (identifier) @function)

(char_literal) @number

(number_literal) @number

(null) @constant

(system_lib_string) @string

(string_literal) @string

";" @delimiter

"." @delimiter

"||" @operator

">" @operator

"==" @operator

"<" @operator

"+=" @operator

"++" @operator

"+" @operator

"&&" @operator

"&" @operator

"*" @operator

"!=" @operator

"=" @operator

"->" @operator

"-=" @operator

"-" @operator

"--" @operator

(preproc_directive) @keyword

"#include" @keyword

"#ifndef" @keyword

"#ifdef" @keyword

"#if" @keyword

"#endif" @keyword

"#else" @keyword

"#elif" @keyword

"#define" @keyword

"while" @keyword

"volatile" @keyword

"union" @keyword

"typedef" @keyword

"switch" @keyword

"struct" @keyword

"static" @keyword

"sizeof" @keyword

"return" @keyword

"inline" @keyword

"if" @keyword

"for" @keyword

"extern" @keyword

"enum" @keyword

"else" @keyword

"do" @keyword

"default" @keyword

"continue" @keyword

"const" @keyword

"case" @keyword

"break" @keyword
