; editor-syntax injections query for glsl. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/glsl/injections.scm (MPL-2.0)
;   helix-editor/helix@079a789e8cb0 runtime/queries/c/injections.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["glsl/injections"].

((comment) @injection.content
 (#set! injection.language "comment"))

((preproc_arg) @injection.content
 (#set! injection.language "c")
 (#set! injection.include-children))

((preproc_arg) @injection.content
 (#set! injection.language "glsl"))
