; editor-syntax highlights query for markdown_inline. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   @tree-sitter-grammars/tree-sitter-markdown@0.3.2 tree-sitter-markdown-inline/queries/highlights.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["markdown_inline/highlights"].

[
  (code_span)
  (link_title)
] @text.literal

[
  (emphasis_delimiter)
  (code_span_delimiter)
] @punctuation.delimiter

(emphasis) @text.emphasis

(strong_emphasis) @text.strong

[
  (link_destination)
  (uri_autolink)
] @text.uri

[
  (link_label)
  (link_text)
  (image_description)
] @text.reference

[
  (backslash_escape)
  (hard_line_break)
] @string.escape

(image ["!" "[" "]" "(" ")"] @punctuation.delimiter)

(inline_link ["[" "]" "(" ")"] @punctuation.delimiter)

(shortcut_link ["[" "]"] @punctuation.delimiter)
