; editor-syntax injections query for markdown_inline. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/markdown.inline/injections.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["markdown_inline/injections"].

((html_tag) @injection.content 
  (#set! injection.language "html") 
  (#set! injection.include-unnamed-children)
  (#set! injection.combined))
