; editor-syntax highlights query for haxe. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-haxe@0.13.0 queries/highlights.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["haxe/highlights"].

(identifier) @variable

(comment) @comment

(preprocessor_statement) @tag

(metadata) @tag

(metadata name: (identifier) @type) @tag

(type_params
  "<" @punctuation.bracket
  ">" @punctuation.bracket
)

(class_declaration name: (identifier) @type.definition)

(interface_declaration name: (identifier) @type.definition)

(typedef_declaration name: (identifier) @type.definition)

(function_declaration name: (identifier) @function)

(function_arg name: (identifier) @variable.parameter)

(call_expression object: [
  (_) @function
  (_ (identifier) @function .)
;   (_(_ (identifier) @function .))
;   (_(_(_ (identifier) @function .)))
;   (_(_(_(_ (identifier) @function .))))
;   (_(_(_(_(_ (identifier) @function .)))))
])

(type_name) @type

(package_name) @module

(type (identifier) !built_in) @type

(type built_in: (identifier)) @type.builtin

[(integer) (float)] @number

(string) @string

(bool) @boolean

(operator) @operator

(escape_sequence) @punctuation

(null) @constant.builtin

(access_identifiers "null" @keyword)

[
  "abstract"
  
  "break"
  "case"
  "cast"
  "catch"
  "class"
  "continue"
  "default"
  "do"
  "dynamic"
  "else"
  "enum"
  "extends"
  "extern"
  "final"
  "for"
  "function"
  "if"
  "implements"
  "import"
  "in"
  "inline"
  "interface"
  "macro"
  "operator"
  "overload"
  "override"
  "package"
  "private"
  "public"
  "return"
  "static"
  "switch"
  "this"
  "throw"
  "try"
  "typedef"
  "untyped"
  "using"
  "var"
  "while"
] @keyword

(function_declaration name: "new" @constructor)

(":") @punctuation.special

(pair [":" "=>"] @punctuation.special)

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
]  @punctuation.bracket

[
;   ";"
;   "?."
;   "."
  ","
] @punctuation.delimiter

(interpolation "$" @punctuation.special)

(interpolation
  "${" @punctuation.special
  "}" @punctuation.special
) @embedded
