; editor-syntax injections query for haxe. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-haxe@0.13.0 queries/injections.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["haxe/injections"].

(interpolation) @haxe

(comment) @jsdoc

(comment) @comment
