; editor-syntax highlights query for dtd. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   @tree-sitter-grammars/tree-sitter-xml@0.7.0 queries/dtd/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["dtd/highlights"].

"xml" @keyword

[ "version" "encoding" ] @property

(EncName) @string.special

(VersionNum) @number

(PI) @embedded

"#PCDATA" @type.builtin

[ "EMPTY" "ANY" ] @string.special.symbol

[ "*" "?" "+" ] @operator

[
  (StringType)
  (TokenizedType)
] @type.builtin

[
  "#REQUIRED"
  "#IMPLIED"
  "#FIXED"
] @attribute

(EntityRef) @constant

(CharRef) @constant

(PEReference) @constant

[ "PUBLIC" "SYSTEM" ] @keyword

(PubidLiteral) @string.special

[
  "<?" "?>"
  "<!" ">"
  "<![" "]]>"
] @punctuation.delimiter

[ "(" ")" "[" ] @punctuation.bracket

[ "\"" "'" ] @punctuation.delimiter

[ "," "|" "=" ] @operator

(Comment) @comment

(ERROR) @error

(PI (PITarget) @keyword)

(elementdecl
  "ELEMENT" @keyword
  (Name) @tag)

(contentspec
  (_ (Name) @property))

(GEDecl
  "ENTITY" @keyword
  (Name) @constant)

(GEDecl (EntityValue) @string)

(NDataDecl
  "NDATA" @keyword
  (Name) @label)

(PEDecl
  "ENTITY" @keyword
  "%" @operator
  (Name) @constant)

(PEDecl (EntityValue) @string)

(NotationDecl
  "NOTATION" @keyword
  (Name) @constant)

(NotationDecl
  (ExternalID
    (SystemLiteral (URI) @string.special)))

(AttlistDecl
  "ATTLIST" @keyword
  (Name) @tag)

(AttDef (Name) @property)

(AttDef (Enumeration (Nmtoken) @string))

(DefaultDecl (AttValue) @string)

(NotationType "NOTATION" @type.builtin)

((EntityRef) @constant.builtin
 (#any-of? @constant.builtin
   "&amp;" "&lt;" "&gt;" "&quot;" "&apos;"))

(SystemLiteral (URI) @markup.link)
