import { writeFileSync, mkdirSync, chmodSync } from "fs"
import { join } from "path"

export function writeCodexConfig(opts: {
  codexHome: string
  shimCommand: string
  shimArgs: string[]
  sessionName: string
  socketsDir: string
  sessionId?: string
}): void {
  mkdirSync(opts.codexHome, { recursive: true, mode: 0o700 })
  const argsToml = JSON.stringify(opts.shimArgs)
  const sessionId = opts.sessionId ?? opts.sessionName
  // MUX_DISPLAY_NAME is what the broker's onRegister handler uses for
  // the session display name.
  const toml = `# Generated by supermux. Do not edit by hand.

[mcp_servers.mux-shim]
command = ${JSON.stringify(opts.shimCommand)}
args = ${argsToml}
env.MUX_SESSION_ID = ${JSON.stringify(sessionId)}
env.MUX_DISPLAY_NAME = ${JSON.stringify(opts.sessionName)}
env.MUX_AGENT_KIND = "codex"
env.MUX_SOCKETS_DIR = ${JSON.stringify(opts.socketsDir)}

# Disable codex's native memory feature — ~/.mux is the sole memory.
[features]
memories = false
`
  const path = join(opts.codexHome, "config.toml")
  writeFileSync(path, toml, { encoding: "utf8", mode: 0o600 })
  chmodSync(path, 0o600)
}
