; editor-syntax folds query for java. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/java/folds.scm (Apache-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["java/folds"].

[
  (block)
  (class_body)
  (constructor_declaration)
  (argument_list)
  (annotation_argument_list)
  (import_declaration)+
] @fold
