; editor-syntax folds query for nginx. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-nginx@1.0.1 queries/folds.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["nginx/folds"].

(block) @fold
