; editor-syntax highlights query for css. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-css@0.25.0 queries/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["css/highlights"].

(comment) @comment

(tag_name) @tag

(nesting_selector) @tag

(universal_selector) @tag

"~" @operator

">" @operator

"+" @operator

"-" @operator

"*" @operator

"/" @operator

"=" @operator

"^=" @operator

"|=" @operator

"~=" @operator

"$=" @operator

"*=" @operator

"and" @operator

"or" @operator

"not" @operator

"only" @operator

(class_name) @property

(id_name) @property

(namespace_name) @property

(property_name) @property

(feature_name) @property

(attribute_name) @attribute

(function_name) @function

"@media" @keyword

"@import" @keyword

"@charset" @keyword

"@namespace" @keyword

"@supports" @keyword

"@keyframes" @keyword

(at_keyword) @keyword

(to) @keyword

(from) @keyword

(important) @keyword

(string_value) @string

(color_value) @string.special

(integer_value) @number

(float_value) @number

(unit) @type

[
  "#"
  ","
  "."
  ":"
  "::"
  ";"
] @punctuation.delimiter

[
  "{"
  ")"
  "("
  "}"
] @punctuation.bracket

(attribute_selector (plain_value) @string)

((property_name) @variable
 (#match? @variable "^--"))

((plain_value) @variable
 (#match? @variable "^--"))

(pseudo_element_selector (tag_name) @attribute)

(pseudo_class_selector (class_name) @attribute)
