; editor-syntax injections query for rust. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-rust@0.24.0 queries/injections.scm (MIT)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["rust/injections"].

((macro_invocation
  (token_tree) @injection.content)
 (#set! injection.language "rust")
 (#set! injection.include-children))

((macro_rule
  (token_tree) @injection.content)
 (#set! injection.language "rust")
 (#set! injection.include-children))
