// scripts/generate-static-manifest.ts
// Overwrites src/channels/web/static-manifest.generated.ts with imports for
// every file under src/channels/web/static (the built PWA). Run AFTER the
// web-app build, BEFORE bun build --compile. Idempotent; never committed.
import { readdirSync, statSync, writeFileSync, existsSync } from "fs"
import { join, relative, resolve } from "path"

const repoRoot = resolve(import.meta.dirname, "..")
const root = join(repoRoot, "src/channels/web/static")
const outFile = join(repoRoot, "src/channels/web/static-manifest.generated.ts")

if (!existsSync(join(root, "index.html"))) {
  console.error(`generate-static-manifest: ${root}/index.html missing — build the PWA first (cd src/web-app && bun run build)`)
  process.exit(1)
}

const files: string[] = []
;(function walk(d: string) {
  for (const e of readdirSync(d)) {
    const p = join(d, e)
    statSync(p).isDirectory() ? walk(p) : files.push(p)
  }
})(root)
files.sort()

let imports = ""
let entries = ""
files.forEach((f, i) => {
  const importPath = "./" + relative(join(repoRoot, "src/channels/web"), f).replaceAll("\\", "/")
  const urlPath = "/" + relative(root, f).replaceAll("\\", "/")
  imports += `import f${i} from ${JSON.stringify(importPath)} with { type: "file" };\n`
  // `with { type: "file" }` yields a path string at runtime for every asset, but
  // bun-types declares `*.html` as HTMLBundle (its non-file HTML bundler), so the
  // index.html binding is typed HTMLBundle, not string. Coerce uniformly so the
  // map stays Record<string, string> regardless of extension. (Asset extensions
  // tsc can't resolve — .css/.png/.svg/.ico/.webmanifest/.js — are declared as
  // string modules in src/types/assets.d.ts so the imports above resolve.)
  entries += `  ${JSON.stringify(urlPath)}: f${i} as unknown as string,\n`
})

writeFileSync(outFile,
  `// GENERATED by scripts/generate-static-manifest.ts — never commit with entries.\n` +
  imports + `\nexport const EMBEDDED_STATIC: Record<string, string> = {\n` + entries + `}\n`)
console.log(`static manifest: ${files.length} files`)
