package dev.supermux.terminal.sample

import kotlin.random.Random

/**
 * The byte streams this sample drives terminals with.
 *
 * **There is no pty here, and no transport.** The sample deliberately depends on nothing but
 * `:terminal-compose` (and through it `:terminal-core`): no broker, no SSH, no shell, no
 * `ProcessBuilder`. Every byte a terminal in this app ever sees is generated by the code below, so
 * a run is reproducible from a seed alone and says something about the ENGINE and the SURFACE
 * rather than about whatever `/bin/bash` happened to print.
 *
 * Each fixture is a [FixtureStream]: a [FixtureStream.preamble] sent once, an unbounded sequence of
 * [FixtureStream.next] chunks, and a [FixtureStream.epilogue] that puts the terminal back the way
 * it found it. Chunks are sized like real pty reads (a few hundred bytes to a few KiB), because
 * feeding one 10 MiB array would measure `memcpy`, not a terminal.
 */
enum class SampleFixture(val id: String, val title: String, val summary: String) {
    /** An interactive shell: prompts, coloured `ls`, a git status, a build log with progress. */
    SHELL(
        id = "shell",
        title = "Shell-like output",
        summary = "Prompts, coloured listings, git status, a build log with carriage-return progress.",
    ),

    /**
     * A full-screen program on the alternate screen that asked for the mouse: modes 1049 (alt
     * screen), 1002 (button-event tracking), 1006 (SGR encoding) and 1007 (alternate scroll). This
     * is the fixture that proves the routing rules — while it runs, the wheel and drags belong to
     * the PROGRAM, not to the local scrollback.
     */
    ALT_SCREEN(
        id = "alt",
        title = "Mouse-enabled alternate screen",
        summary = "A TUI on the alternate screen with mouse tracking (1049/1002/1006/1007).",
    ),

    /** Wide glyphs, combining marks, emoji (ZWJ sequences), box drawing and every SGR attribute. */
    UNICODE(
        id = "unicode",
        title = "Unicode and styles",
        summary = "CJK, combining marks, ZWJ emoji, box drawing, 256-colour, truecolour, every SGR.",
    ),

    /** Dense, mostly-plain output as fast as the rate allows — the throughput and eviction case. */
    SUSTAINED(
        id = "sustained",
        title = "Sustained output",
        summary = "Dense log lines at the configured rate; fills and evicts scrollback continuously.",
    ),
    ;

    /** A fresh, deterministic stream of this fixture. The same [seed] always produces the same bytes. */
    fun stream(seed: Long = DEFAULT_SEED): FixtureStream = when (this) {
        SHELL -> ShellStream(Random(seed))
        ALT_SCREEN -> AlternateScreenStream(Random(seed))
        UNICODE -> UnicodeStream(Random(seed))
        SUSTAINED -> SustainedStream(Random(seed))
    }

    companion object {
        /** Fixed on purpose: two runs of this sample feed byte-identical streams. */
        const val DEFAULT_SEED: Long = 0x5EEDL

        fun byId(id: String): SampleFixture? = entries.firstOrNull { it.id == id }
    }
}

/**
 * One fixture's bytes. Not thread-safe: one stream belongs to one producer coroutine.
 *
 * [next] never returns an empty array and never ends — a terminal sample is interesting precisely
 * because the output does not stop.
 */
interface FixtureStream {
    /** Sent once before the first [next]; empty when the fixture needs no setup. */
    fun preamble(): ByteArray = ByteArray(0)

    /** The next pty-read-sized chunk. */
    fun next(): ByteArray

    /** Sent once when the fixture stops, to undo [preamble]. */
    fun epilogue(): ByteArray = ByteArray(0)
}

// ---------------------------------------------------------------------------------------------
// Shared vocabulary
// ---------------------------------------------------------------------------------------------

private const val ESC = "\u001b"
private const val CSI = "$ESC["
private const val RESET = "${CSI}0m"

private val WORDS = listOf(
    "session", "broker", "viewport", "ghostty", "surface", "palette", "scrollback", "grapheme",
    "mailbox", "renderer", "codec", "manifest", "dispatcher", "cluster", "snapshot", "lease",
)

private val PATHS = listOf(
    "src/commonMain/kotlin/TerminalSession.kt", "native/terminal_jni.c", "wasm/terminal-loader.mjs",
    "build/gradle/generated/jniLibs", "apps/terminal-compose/src/commonMain", "docs/spec.md",
)

private fun Random.word(): String = WORDS[nextInt(WORDS.size)]

private fun Random.path(): String = PATHS[nextInt(PATHS.size)]

// ---------------------------------------------------------------------------------------------
// 1. Shell-like output
// ---------------------------------------------------------------------------------------------

private class ShellStream(private val random: Random) : FixtureStream {
    private var step = 0

    override fun next(): ByteArray {
        val out = StringBuilder(1024)
        // One "command" per chunk: the prompt, then whatever it printed. That is the rhythm a
        // shell actually has, and it is what makes the scrollback look like a session rather than
        // like a file.
        out.append("${CSI}1;32muser${RESET}@${CSI}1;34mmini${RESET}:${CSI}1;36m~/work${RESET}$ ")
        when (step++ % 4) {
            0 -> {
                out.append("ls -la\r\n")
                repeat(6 + random.nextInt(10)) {
                    val dir = random.nextBoolean()
                    val colour = if (dir) "1;34" else "0"
                    out.append("drwxr-xr-x  ${random.nextInt(1, 40)} user user ")
                    out.append("${random.nextInt(100, 99999)} Sep ${random.nextInt(1, 28)} ")
                    out.append("${CSI}${colour}m${random.word()}${if (dir) "/" else ".kt"}$RESET\r\n")
                }
            }
            1 -> {
                out.append("git status\r\n")
                out.append("On branch ${CSI}1;33mmux/terminal${RESET}\r\n")
                out.append("Changes not staged for commit:\r\n")
                repeat(3 + random.nextInt(6)) {
                    out.append("\tmodified:   ${CSI}31m${random.path()}$RESET\r\n")
                }
                out.append("\r\nno changes added to commit\r\n")
            }
            2 -> {
                out.append("./gradlew :terminal-core:jvmTest\r\n")
                // Carriage-return progress: the same line rewritten, which is the case a renderer
                // that redraws whole screens gets wrong and a dirty-row one gets right.
                repeat(20) { percent ->
                    out.append("\r${CSI}2m[")
                    val filled = percent * 40 / 20
                    out.append("=".repeat(filled))
                    out.append(" ".repeat(40 - filled))
                    out.append("] ${percent * 5}%$RESET")
                }
                out.append("\r\n${CSI}1;32mBUILD SUCCESSFUL${RESET} in ${random.nextInt(4, 90)}s\r\n")
            }
            else -> {
                out.append("tail -f build.log\r\n")
                repeat(8 + random.nextInt(8)) {
                    val level = random.nextInt(10)
                    val (tag, colour) = when {
                        level < 6 -> "INFO " to "0;37"
                        level < 9 -> "WARN " to "0;33"
                        else -> "ERROR" to "1;31"
                    }
                    out.append("${CSI}2m12:0${random.nextInt(10)}:${random.nextInt(10, 60)}$RESET ")
                    out.append("${CSI}${colour}m$tag$RESET ")
                    out.append("${random.word()}: ${random.word()} ${random.nextInt(1000)} ")
                    out.append("(${random.path()})\r\n")
                }
            }
        }
        return out.toString().encodeToByteArray()
    }
}

// ---------------------------------------------------------------------------------------------
// 2. Mouse-enabled alternate screen
// ---------------------------------------------------------------------------------------------

private class AlternateScreenStream(private val random: Random) : FixtureStream {
    private var tick = 0

    override fun preamble(): ByteArray =
        // 1049: alternate screen (no scrollback of its own), 1002: button-event tracking,
        // 1006: SGR mouse encoding, 1007: alternate scroll, 25l: the program draws its own cursor.
        "$CSI?1049h$CSI?1002h$CSI?1006h$CSI?1007h$CSI?25l${CSI}2J".encodeToByteArray()

    override fun epilogue(): ByteArray =
        "$CSI?1007l$CSI?1006l$CSI?1002l$CSI?25h$CSI?1049l".encodeToByteArray()

    override fun next(): ByteArray {
        val out = StringBuilder(2048)
        val frame = tick++
        // A pager-like pane: a title row, a list whose selection moves, and a status bar. Every
        // chunk repaints by ADDRESSING cells rather than by clearing the screen, which is what a
        // real TUI does and what makes the dirty-row path do any work at all.
        out.append("${CSI}1;1H${CSI}7m")
        out.append(" supermux terminal sample — alternate screen, mouse tracking on ".padEnd(120))
        out.append(RESET)
        for (row in 0 until 30) {
            val selected = (frame + row) % 30 == 0
            out.append("$CSI${row + 3};1H")
            if (selected) out.append("${CSI}44;97m") else out.append("${CSI}0m")
            val line = " ${(row + 1).toString().padStart(3)}  ${random.path().padEnd(52)}  " +
                "${random.nextInt(10, 9999)} B  ${random.word()}"
            out.append(line.take(118).padEnd(118))
            out.append(RESET)
        }
        out.append("$CSI${38};1H${CSI}2m")
        out.append(" frame $frame · q quit · wheel scrolls the PROGRAM (mode 1002/1007) ".padEnd(118))
        out.append(RESET)
        return out.toString().encodeToByteArray()
    }
}

// ---------------------------------------------------------------------------------------------
// 3. Unicode and styles
// ---------------------------------------------------------------------------------------------

private val CJK = "语言模型终端渲染器宽字符测试样本网格对齐"
private val COMBINING = listOf("á", "ê", "ö", "ñ", "ů", "ç")
private val EMOJI = listOf("😀", "🚀", "🧵", "👩‍💻", "🏳️‍🌈", "👨‍👩‍👧‍👦", "🇹🇷", "⚙️")
private val BOX = "─│┌┐└┘├┤┬┴┼━┃┏┓┗┛╔╗╚╝║═"

private class UnicodeStream(private val random: Random) : FixtureStream {
    private var step = 0

    override fun next(): ByteArray {
        val out = StringBuilder(2048)
        when (step++ % 5) {
            0 -> {
                out.append("${CSI}1mSGR attributes${RESET}\r\n")
                // Every flag CellFlags knows, plus every Underline kind, one per line.
                val attributes = listOf(
                    1 to "bold", 2 to "faint", 3 to "italic", 4 to "underline", 5 to "blink",
                    7 to "inverse", 9 to "strikethrough", 53 to "overline",
                )
                for ((code, name) in attributes) {
                    out.append("$CSI${code}m$name — ${random.word()} ${CJK.take(6)}$RESET\r\n")
                }
                for (kind in 1..5) {
                    out.append("${CSI}4:${kind}m${CSI}58;5;${random.nextInt(9, 15)}m")
                    out.append("underline style $kind$RESET\r\n")
                }
            }
            1 -> {
                out.append("${CSI}1m256-colour cube${RESET}\r\n")
                for (row in 0 until 6) {
                    for (col in 0 until 36) {
                        val index = 16 + row * 36 + col
                        out.append("${CSI}48;5;${index}m ")
                    }
                    out.append("$RESET\r\n")
                }
            }
            2 -> {
                out.append("${CSI}1mTruecolour ramp${RESET}\r\n")
                for (row in 0 until 3) {
                    for (col in 0 until 100) {
                        val r = (col * 255 / 99)
                        val g = (row * 120 + col) % 256
                        val b = 255 - r
                        out.append("${CSI}48;2;$r;$g;${b}m ")
                    }
                    out.append("$RESET\r\n")
                }
            }
            3 -> {
                out.append("${CSI}1mWide, combining, emoji${RESET}\r\n")
                repeat(8) {
                    out.append("  ")
                    out.append(CJK.drop(random.nextInt(CJK.length - 8)).take(8))
                    out.append("  ")
                    repeat(6) { out.append(COMBINING[random.nextInt(COMBINING.size)]) }
                    out.append("  ")
                    repeat(4) { out.append(EMOJI[random.nextInt(EMOJI.size)]) }
                    out.append("\r\n")
                }
            }
            else -> {
                out.append("${CSI}1mBox drawing${RESET}\r\n")
                out.append("┏").append("━".repeat(60)).append("┓\r\n")
                repeat(6) {
                    out.append("┃ ")
                    val body = StringBuilder()
                    while (body.length < 58) body.append(BOX[random.nextInt(BOX.length)])
                    out.append(body.take(58))
                    out.append(" ┃\r\n")
                }
                out.append("┗").append("━".repeat(60)).append("┛\r\n")
                // OSC 8 hyperlink + OSC 0 title: the two effects the surface reports to its host.
                out.append("${ESC}]8;;https://ghostty.org${ESC}\\ghostty.org${ESC}]8;;${ESC}\\\r\n")
                out.append("${ESC}]0;terminal-sample · unicode${ESC}\\")
            }
        }
        return out.toString().encodeToByteArray()
    }
}

// ---------------------------------------------------------------------------------------------
// 4. Sustained output
// ---------------------------------------------------------------------------------------------

private class SustainedStream(private val random: Random) : FixtureStream {
    private var line = 0L

    override fun next(): ByteArray {
        // ~4 KiB per chunk: big enough that the rate limiter is not the bottleneck, small enough
        // that one chunk cannot monopolise a batch of the session's owner loop.
        val out = StringBuilder(4096)
        while (out.length < 4000) {
            val number = line++
            out.append("${CSI}2m${number.toString().padStart(9, '0')}$RESET ")
            if (number % 17 == 0L) out.append("${CSI}33m")
            repeat(7) { out.append(random.word()).append(' ') }
            out.append(random.path())
            if (number % 17 == 0L) out.append(RESET)
            out.append("\r\n")
        }
        return out.toString().encodeToByteArray()
    }
}

// ---------------------------------------------------------------------------------------------
// Benchmark fixtures: fixed size, byte-for-byte repeatable
// ---------------------------------------------------------------------------------------------

/** The two fixed streams the benchmark feeds; see [benchmarkFixture]. */
enum class BenchmarkFixture(val id: String) {
    /** Plain UTF-8 text, no escape sequences at all: the parser's cheapest path. */
    PLAIN("plain"),

    /** The same volume with SGR, cursor addressing and erase sequences mixed in. */
    ANSI("ansi"),
    ;

    companion object {
        fun byId(id: String): BenchmarkFixture? = entries.firstOrNull { it.id == id }
    }
}

/**
 * Exactly [totalBytes] bytes of [fixture], split into ~[chunkBytes] chunks, generated from [seed].
 *
 * Built once and replayed: the benchmark must feed the SAME bytes every repeat, or "the second ten
 * minutes were slower" could just mean "the second ten minutes had more escape sequences". The last
 * chunk is trimmed so the total is exact.
 */
fun benchmarkFixture(
    fixture: BenchmarkFixture,
    totalBytes: Int = 10 * 1024 * 1024,
    chunkBytes: Int = 4096,
    seed: Long = SampleFixture.DEFAULT_SEED,
): List<ByteArray> {
    require(totalBytes > 0 && chunkBytes > 0)
    val random = Random(seed)
    val chunks = ArrayList<ByteArray>(totalBytes / chunkBytes + 1)
    var produced = 0
    val builder = StringBuilder(chunkBytes + 256)
    while (produced < totalBytes) {
        builder.setLength(0)
        while (builder.length < chunkBytes) {
            when (fixture) {
                BenchmarkFixture.PLAIN -> {
                    repeat(9) { builder.append(random.word()).append(' ') }
                    builder.append(random.path()).append("\r\n")
                }
                BenchmarkFixture.ANSI -> {
                    builder.append("${CSI}2m").append(random.nextInt(100000).toString().padStart(6, '0'))
                    builder.append(RESET).append(' ')
                    builder.append("${CSI}38;5;${random.nextInt(16, 232)}m")
                    repeat(5) { builder.append(random.word()).append(' ') }
                    builder.append(RESET)
                    builder.append("${CSI}1;4m").append(random.path()).append(RESET)
                    // A cursor move + erase-to-end, the pair every progress line uses.
                    builder.append("${CSI}K\r\n")
                }
            }
        }
        var bytes = builder.toString().encodeToByteArray()
        if (produced + bytes.size > totalBytes) bytes = bytes.copyOf(totalBytes - produced)
        produced += bytes.size
        chunks += bytes
    }
    return chunks
}
