; editor-syntax folds query for pascal. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   nvim-treesitter/nvim-treesitter@f603a2f4da48 runtime/queries/pascal/folds.scm (Apache-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["pascal/folds"].

[
  (interface)
  (implementation)
  (initialization)
  (finalization)
  (if)
  (ifElse)
  (while)
  (repeat)
  (for)
  (foreach)
  (try)
  (case)
  (caseCase)
  (asm)
  (with)
  (declVar)
  (declConst)
  (declEnum)
  (declProcRef)
  (declExports)
  (declType)
  (defProc)
  (declField)
  (declProp)
  (comment)
] @fold

(interface
  (declProc) @fold)
