; editor-syntax highlights query for pascal. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-pascal@0.0.1 queries/highlights.scm (MIT)
;   (patterns reversed: written for EARLIER-pattern-wins; this file gives the LATER pattern precedence)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["pascal/highlights"].

(identifier)      @identifier

(exprArgs ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(exprTpl args: ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(exprParens ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(exprBrackets ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(assignment rhs: ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(exprUnary ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(exprBinary ((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$|^[a-z]{2}[A-Z].+$")))

(declEnumValue name: (identifier) @constant)

(declConst name: (identifier) @constant)

(declField name: (identifier) @variable)

(declVar name: (identifier) @variable)

(statement (exprDot rhs: (exprTpl entity: (identifier) @function)))

(statement (exprTpl entity: (identifier) @function))

(statement (exprDot rhs: (identifier) @function))

(statement (identifier) @function)

(exprCall entity: (exprDot rhs: (exprTpl entity: (identifier) @function)))

(exprCall entity: (exprDot rhs: (identifier) @function))

(exprCall entity: (exprTpl entity: (identifier) @function))

(exprCall entity: (identifier) @function)

(statement ((identifier) @keyword
 (#match? @keyword "^[cC][oO][nN][tT][iI][nN][uU][eE]$")))

(statement ((identifier) @keyword
 (#match? @keyword "^[bB][rR][eE][aA][kK]$")))

(statement (exprCall entity: ((identifier) @keyword
 (#match? @keyword "^[eE][xX][iI][tT]$"))))

(statement ((identifier) @keyword
 (#match? @keyword "^[eE][xX][iI][tT]$")))

[
	(caseLabel)
	(label)
] @constant

(typeref) @type

(exceptionHandler variable: (identifier) @variable.parameter)

(genericDot (genericTpl entity: (identifier) @type))

(genericDot (identifier) @type)

(genericArg	type: (typeref) @type)

(genericArg	name: (identifier) @type.parameter)

(declArg name: (identifier) @variable.parameter)

(declProp name: (identifier) @function)

(declProc name: (genericDot rhs: (genericTpl entity: (identifier) @function)))

(declProc name: (genericDot rhs: (identifier) @function))

(declProc name: (genericTpl entity: (identifier) @function))

(declProc name: (identifier) @function)

(declType name: (genericTpl entity: (identifier) @type))

(declType name: (identifier) @type)

(pp)              @keyword

(comment)         @comment

(literalString)   @string

(literalNumber)   @number

[
	(kNil)
] @keyword

[
	(kTrue)
	(kFalse)
] @constant

[
	(kOr)
	(kXor)
	(kDiv)
	(kMod)
	(kAnd)
	(kShl)
	(kShr)
	(kNot)
	(kIs)
	(kAs)
	(kIn)
] @keyword

[
	(kDot)
	(kAdd)
	(kSub)
	(kMul)
	(kFdiv)
	(kAssign)
	(kAssignAdd)
	(kAssignSub)
	(kAssignMul)
	(kAssignDiv)
	(kEq)
	(kLt)
	(kLte)
	(kGt)
	(kGte)
	(kNeq)
	(kAt)
	(kHat)
] @operator

[
	";"
	","
	":"
	".."
	(kEndDot)
] @punctuation.delimiter

[
	"("
	")"
	"["
	"]"
] @punctuation.bracket

[
	(kProgram)
	(kLibrary)
	(kUnit)
	(kUses)

	(kBegin)
	(kEnd)
	(kAsm)

	(kVar)
	(kThreadvar)
	(kConst)
	(kResourcestring)
	(kConstref)
	(kOut)
	(kType)
	(kLabel)
	(kExports)

	(kAbsolute)

	(kProperty)
	(kRead)
	(kWrite)
	(kImplements)
	(kDefault)
	(kNodefault)
	(kStored)
	(kIndex)

	(kClass)
	(kInterface)
	(kObject)
	(kRecord)
	(kObjcclass)
	(kObjccategory)
	(kObjcprotocol)
	(kArray)
	(kFile)
	(kString)
	(kSet)
	(kOf)
	(kHelper)
	(kPacked)

	(kGeneric)
	(kSpecialize)

	(kFunction)
	(kProcedure)
	(kConstructor)
	(kDestructor)
	(kOperator)
	(kReference)

	(kInterface)
	(kImplementation)
	(kInitialization)
	(kFinalization)

	(kPublished)
	(kPublic)
	(kProtected)
	(kPrivate)
	(kStrict)
	(kRequired)
	(kOptional)

	(kForward)

	(kStatic)
	(kVirtual)
	(kAbstract)
	(kSealed)
	(kDynamic)
	(kOverride)
	(kOverload)
	(kReintroduce)
	(kInherited)
	(kInline)

	(kStdcall)
	(kCdecl)
	(kCppdecl)
	(kPascal)
	(kRegister)
	(kMwpascal)
	(kExternal)
	(kName)
	(kMessage)
	(kDeprecated)
	(kExperimental)
	(kPlatform)
	(kUnimplemented)
	(kCvar)
	(kExport)
	(kFar)
	(kNear)
	(kSafecall)
	(kAssembler)
	(kNostackframe)
	(kInterrupt)
	(kNoreturn)
	(kIocheck)
	(kLocal)
	(kHardfloat)
	(kSoftfloat)
	(kMs_abi_default)
	(kMs_abi_cdecl)
	(kSaveregisters)
	(kSysv_abi_default)
	(kSysv_abi_cdecl)
	(kVectorcall)
	(kVarargs)
	(kWinapi)
	(kAlias)
	(kDelayed)

	(kFor)
	(kTo)
	(kDownto)
	(kIf)
	(kThen)
	(kElse)
	(kDo)
	(kWhile)
	(kRepeat)
	(kUntil)
	(kTry)
	(kExcept)
	(kFinally)
	(kRaise)
	(kOn)
	(kCase)
	(kWith)
	(kGoto)
] @keyword
