; editor-syntax folds query for julia. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   helix-editor/helix@079a789e8cb0 runtime/queries/julia/folds.scm (MPL-2.0)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["julia/folds"].

[
  (module_definition)
  (struct_definition)
  (macro_definition)
  (function_definition)
  (if_statement)
  (try_statement)
  (for_statement)
  (while_statement)
  (let_statement)
  (quote_statement)
  (do_clause)
  (compound_statement) ; begin block
] @fold
