import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { codexCredentialFreshness, promoteIfNewer } from "./credentials.js"
import { ENVIRONMENT_FIELDS, requireSpec, validateMcpServerNames } from "./spec.js"
import type { CodexEnvironmentSpec, McpServerSpec, PreparedEnvironment } from "./types.js"
import { copyFileReplace, writeFileNoFollow } from "./write.js"

function ensureHome(home: string): void {
  mkdirSync(home, { recursive: true, mode: 0o700 })
}

function renderCodexConfig(spec: CodexEnvironmentSpec): string {
  const servers = spec.mcpServers.map(renderCodexMcp).join("\n")
  return `# Generated by supermux. Do not edit by hand.
${servers}
# Disable codex's native memory feature — ~/.mux is the sole memory.
[features]
memories = ${spec.nativeMemory}
`
}

function renderCodexMcp(server: McpServerSpec): string {
  const envLines = Object.entries(server.env)
    .map(([key, value]) => `env.${key} = ${JSON.stringify(value)}`)
    .join("\n")
  return `
[mcp_servers.${server.name}]
command = ${JSON.stringify(server.command)}
args = ${JSON.stringify(server.args)}
${envLines}
`
}

export async function prepareCodexEnvironment(spec: CodexEnvironmentSpec): Promise<PreparedEnvironment> {
  requireSpec(spec, [
    ...ENVIRONMENT_FIELDS,
    "credentials",
    "credentials.apiKey",
    "credentials.canonicalHome",
    "nativeMemory",
  ])
  validateMcpServerNames(spec.mcpServers)
  ensureHome(spec.home)
  const files: string[] = []

  let credentials: PreparedEnvironment["credentials"]
  const env: Record<string, string> = { CODEX_HOME: spec.home }

  if (spec.credentials.apiKey) {
    credentials = "api_key"
    env.OPENAI_API_KEY = spec.credentials.apiKey
  } else {
    const userAuth = join(spec.credentials.canonicalHome, "auth.json")
    const sessionAuth = join(spec.home, "auth.json")
    // Heal first, copy second. A token this session refreshed goes back to the
    // user's file BEFORE the copy below overwrites it, so a sibling session gets
    // the refreshed token instead of the token it replaced.
    promoteIfNewer({
      sessionCopy: sessionAuth,
      canonical: userAuth,
      freshness: codexCredentialFreshness,
    })
    if (existsSync(userAuth)) {
      copyFileReplace(userAuth, sessionAuth)
      files.push(sessionAuth)
      credentials = "copy"
    } else {
      throw new Error(
        `Codex auth not found at ${userAuth} and OPENAI_API_KEY is unset. ` +
        `Run \`codex login\` first.`,
      )
    }
  }

  const configPath = join(spec.home, "config.toml")
  writeFileSync(configPath, renderCodexConfig(spec), { encoding: "utf8", mode: 0o600 })
  chmodSync(configPath, 0o600)
  files.push(configPath)

  if (spec.instructions !== null) {
    const dest = join(spec.home, "AGENTS.md")
    writeFileNoFollow(dest, spec.instructions, 0o600)
    chmodSync(dest, 0o600)
    files.push(dest)
  }

  return { env, files, credentials }
}
