import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { grokCredentialExpiry, promoteCredential } from "./credentials.js"
import { ENVIRONMENT_FIELDS, requireSpec, validateMcpServerNames } from "./spec.js"
import type { GrokEnvironmentSpec, McpServerSpec, PreparedEnvironment } from "./types.js"
import { lstatSafe, writeFileNoFollow } from "./write.js"

function tomlStr(v: string): string {
  return JSON.stringify(v)
}

function ensureHome(home: string): void {
  mkdirSync(home, { recursive: true, mode: 0o700 })
}

function renderGrokConfig(spec: GrokEnvironmentSpec): string {
  const skillsBlock = spec.skillsPaths.length
    ? `\n[skills]\npaths = [${spec.skillsPaths.map(tomlStr).join(", ")}]\n`
    : ""
  const claudeBlock = spec.importClaudeConfig
    ? ""
    : `[claude_compat]
imported = true
`
  const servers = spec.mcpServers.map(renderGrokMcp).join("")
  return `# Generated by supermux — session-private grok config. Do not edit.
[cli]
# grok defaults to checking for updates on every launch, and the broker launches a
# child per session — so the binary could change mid-conversation, versions could
# drift between concurrent sessions, and every spawn would pay a network round-trip.
# Pinned off for broker-driven sessions only; the user's own ~/.grok/config.toml is
# untouched, so interactive \`grok\` still auto-updates as they configured it.
auto_update = ${spec.autoUpdate}

${claudeBlock}${skillsBlock}${servers}`
}

function renderGrokMcp(server: McpServerSpec): string {
  const args = server.args.map(tomlStr).join(", ")
  const envLines = Object.entries(server.env)
    .map(([key, value]) => `${key} = ${tomlStr(value)}`)
    .join("\n")
  const envBlock = envLines ? `\n[mcp_servers.${server.name}.env]\n${envLines}\n` : "\n"
  return `[mcp_servers.${server.name}]
command = ${tomlStr(server.command)}
args = [${args}]
enabled = true
${envBlock}`
}

function writeGrokInstructions(workdir: string, body: string): string {
  const agents = join(workdir, "AGENTS.md")
  const st = lstatSafe(agents)
  const target = st && !st.isSymbolicLink() ? "AGENTS.override.md" : "AGENTS.md"
  const path = join(workdir, target)
  writeFileNoFollow(path, body, 0o644)
  excludeFromGit(workdir, target)
  return path
}

function excludeFromGit(workdir: string, rel: string): void {
  const infoDir = join(workdir, ".git", "info")
  if (!existsSync(infoDir)) return
  const excludePath = join(infoDir, "exclude")
  const current = existsSync(excludePath) ? readFileSync(excludePath, "utf8") : ""
  if (current.split("\n").includes(rel)) return
  appendFileSync(excludePath, (current.endsWith("\n") || current === "" ? "" : "\n") + rel + "\n", "utf8")
}

function grokEnv(home: string, authPath: string, platform: NodeJS.Platform): Record<string, string> {
  return {
    HOME: home,
    GROK_AUTH_PATH: authPath,
    ...(platform === "win32" ? { USERPROFILE: home } : {}),
  }
}

export async function prepareGrokEnvironment(spec: GrokEnvironmentSpec): Promise<PreparedEnvironment> {
  requireSpec(spec, [
    ...ENVIRONMENT_FIELDS,
    "credentials",
    "credentials.canonicalAuthPath",
    "autoUpdate",
    "importClaudeConfig",
    "platform",
  ])
  validateMcpServerNames(spec.mcpServers)
  ensureHome(spec.home)
  const sessionGrokDir = join(spec.home, ".grok")
  mkdirSync(sessionGrokDir, { recursive: true, mode: 0o700 })
  const files: string[] = []

  const src = spec.credentials.canonicalAuthPath
  const dest = join(sessionGrokDir, "auth.json")
  let credentials: PreparedEnvironment["credentials"] = "none"
  let authPath = src
  try {
    const current = lstatSafe(dest)
    if (current?.isFile() && (!existsSync(src) || grokCredentialExpiry(dest) > grokCredentialExpiry(src))) {
      try {
        promoteCredential(dest, src)
      } catch {
        credentials = "copy"
        authPath = dest
        return finishGrok(spec, files, grokEnv(spec.home, authPath, spec.platform), credentials)
      }
    }
    if (existsSync(src)) {
      credentials = "canonical"
      authPath = src
    } else {
      credentials = "none"
      authPath = src
    }
  } catch {
    if (existsSync(dest)) {
      credentials = "copy"
      authPath = dest
    } else {
      credentials = existsSync(src) ? "canonical" : "none"
      authPath = src
    }
  }

  return finishGrok(spec, files, grokEnv(spec.home, authPath, spec.platform), credentials)
}

function finishGrok(
  spec: GrokEnvironmentSpec,
  files: string[],
  env: Record<string, string>,
  credentials: PreparedEnvironment["credentials"],
): PreparedEnvironment {
  const grokDir = join(spec.home, ".grok")
  mkdirSync(grokDir, { recursive: true, mode: 0o700 })
  const configPath = join(grokDir, "config.toml")
  writeFileNoFollow(configPath, renderGrokConfig(spec), 0o600)
  chmodSync(configPath, 0o600)
  files.push(configPath)
  if (spec.instructions !== null) {
    files.push(writeGrokInstructions(spec.workdir, spec.instructions))
  }
  return { env, files, credentials }
}
