; editor-syntax highlights query for fsharp_signature. GENERATED by tools/fetch-queries.py from
; native/queries.lock.json: do not edit. Sources, in order:
;   tree-sitter-fsharp@0.3.12 fsharp_signature/queries/highlights.scm (MIT)
;   (its catch-all patterns hoisted to the top: the LATER pattern wins, as in tree-sitter 0.25)
; Each file keeps its source's licence. Rewritten and dropped patterns: the lock's notes["fsharp_signature/highlights"].

[
  (line_comment)
  (xml_doc)
  (block_comment)
] @spell @comment

(xml_doc) @spell @comment.documentation

[
 (atomic_type)
 (simple_type)
 (generic_type)
 (function_type)
 (compound_type)
 (postfix_type)
 (list_type)
 (static_type)
 (constrained_type)
 (flexible_type)
 (byref_type)
 (paren_type)
 (struct_type)
] @type

(wildcard_pattern) @character.special

(argument_patterns) @variable.parameter

[
  (xint)
  (int)
  (int16)
  (uint16)
  (int32)
  (uint32)
  (int64)
  (uint64)
  (nativeint)
  (unativeint)
] @number

[
  (ieee32)
  (ieee64)
  (float)
  (decimal)
] @number.float

(bool) @boolean

(compiler_directive_decl) @keyword.directive

[
  "("
  ")"
  "{"
  "}"
  "["
  "]"
  "[|"
  "|]"
  "{|"
  "|}"
] @punctuation.bracket

[
  "[<"
  ">]"
] @punctuation.special

[
  ","
  ":"
  "."
] @punctuation.delimiter

[
  "|"
  "="
  "->"
  "*"
  (op_identifier)
] @operator

[
  "when"
  "then"
] @keyword.conditional

[
  "and"
  "or"
  "not"
] @keyword.operator

[
  "open"
  "#r"
  "#load"
] @keyword.import

[
  "abstract"
  "delegate"
  "extern"
  "static"
  "inline"
  "mutable"
  "override"
  "rec"
  "global"
  (access_modifier)
] @keyword.modifier

[
  "let"
  "member"
] @keyword.function

[
  "enum"
  "type"
  "exception"
  "inherit"
  "interface"
  "and"
  "class"
  "struct"
] @keyword.type

[
  "as"
  "begin"
  "end"
  "default"
  "do"
  "get"
  "set"
  "new"
  "of"
  "struct"
  "val"
  "module"
  "namespace"
  "with"
] @keyword

[
  "null"
] @constant.builtin

(preproc_inactive) @comment

(const
  [
   (_) @constant
   (unit) @constant.builtin
  ])

(primary_constr_args (_) @variable.parameter)

(class_as_reference
  (_) @variable.parameter.builtin)

((argument_patterns (long_identifier (identifier) @character.special))
 (#match? @character.special "^_"))

(type_name type_name: (_) @type.definition)

(exception_definition exception_name: (_) @type.definition)

(member_signature
  .
  (identifier) @function.member)

(member_signature
  (curried_spec
    (arguments_spec
      "*"* @operator
      (argument_spec
        (argument_name_spec
          "?"? @character.special
          name: (_) @variable.parameter)))))

(union_type_case (identifier) @constant)

(identifier_pattern
  .
  (_) @constant
  .
  (_) @variable)

(optional_pattern
  "?" @character.special)

(fsi_directive_decl . (string) @module)

(import_decl . (_) @module)

(named_module
  name: (_) @module)

(namespace
  name: (_) @module)

(module_defn
  .
  (_) @module)

(record_fields
  (record_field
    .
    (identifier) @property))

(value_declaration_left . (_) @variable)

(function_declaration_left
  . (_) @function)

(typed_pattern
  . (_) @variable.parameter)

(member_defn
  (method_or_prop_defn
    (property_or_ident . (identifier) @function .)
    args: (_)* @variable.parameter))

(member_defn
  (method_or_prop_defn
    (property_or_ident
      instance: (identifier) @variable.parameter.builtin
      method: (identifier) @function.method)
    args: (_)* @variable.parameter))

([
  (string)
  (triple_quoted_string)
  (verbatim_string)
  (char)
  (format_string)
  (format_triple_quoted_string)
] @spell @string)

(preproc_line
  "#line" @keyword.directive)

(attribute
  target: (identifier)? @keyword
  (simple_type) @attribute)

(generic_type
  [
   "<"
   ">"
  ] @punctuation.bracket)

(preproc_if
  [
    "#if" @keyword.directive
    "#endif" @keyword.directive
  ]
  condition: (_)? @keyword.directive)

(preproc_else
  "#else" @keyword.directive)

((long_identifier
  (identifier)+ @variable.member
  .
  (identifier)))

(namespace name: (long_identifier (identifier) @module))

(named_module name: (long_identifier (identifier) @module))

(import_decl (long_identifier (identifier) @module))

(module_abbrev (long_identifier (identifier) @module))

(simple_type (long_identifier (identifier) @type))

(attribute (simple_type (long_identifier (identifier) @attribute)))

((simple_type
   (long_identifier
     (identifier) @type.builtin))
 (#any-of? @type.builtin "bool" "byte" "sbyte" "int16" "uint16" "int" "uint" "int64" "uint64" "nativeint" "unativeint" "decimal" "float" "double" "float32" "single" "char" "string" "unit"))

((identifier) @module.builtin
 (#any-of? @module.builtin "Array" "Async" "Directory" "File" "List" "Option" "Path" "Map" "Set" "Lazy" "Seq" "Task" "String" "Result" ))
